// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scptasks

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpTasksDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		MarkdownDescription: "Get all tasks",
		Attributes: map[string]schema.Attribute{
			"limit": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				Validators: []validator.Int64{
					int64validator.Between(0, 2147483647),
				},
			},
			"offset": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				Validators: []validator.Int64{
					int64validator.Between(0, 2147483647),
				},
			},
			"q": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Search ignoring case within the properties name, uuid, server name, server nickname and server uuid",
				MarkdownDescription: "Search ignoring case within the properties name, uuid, server name, server nickname and server uuid",
			},
			"scp_tasks": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"executing_user": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"company": schema.StringAttribute{
									Computed: true,
								},
								"email": schema.StringAttribute{
									Computed: true,
								},
								"firstname": schema.StringAttribute{
									Computed: true,
								},
								"id": schema.Int64Attribute{
									Computed: true,
								},
								"lastname": schema.StringAttribute{
									Computed: true,
								},
								"username": schema.StringAttribute{
									Computed: true,
								},
							},
							CustomType: ExecutingUserType{
								ObjectType: types.ObjectType{
									AttrTypes: ExecutingUserValue{}.AttributeTypes(ctx),
								},
							},
							Computed: true,
						},
						"finished_at": schema.StringAttribute{
							Computed: true,
						},
						"message": schema.StringAttribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"on_rollback": schema.BoolAttribute{
							Computed: true,
						},
						"started_at": schema.StringAttribute{
							Computed: true,
						},
						"state": schema.StringAttribute{
							Computed: true,
						},
						"task_progress": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"expected_finished_at": schema.StringAttribute{
									Computed: true,
								},
								"progress_in_percent": schema.Float64Attribute{
									Computed: true,
								},
							},
							CustomType: TaskProgressType{
								ObjectType: types.ObjectType{
									AttrTypes: TaskProgressValue{}.AttributeTypes(ctx),
								},
							},
							Computed: true,
						},
						"uuid": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: ScpTasksType{
						ObjectType: types.ObjectType{
							AttrTypes: ScpTasksValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"server_id": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"state": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Filter by state (ROLLBACK is not supported)",
				MarkdownDescription: "Filter by state (ROLLBACK is not supported)",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"PENDING",
						"RUNNING",
						"FINISHED",
						"ERROR",
						"WAITING_FOR_CANCEL",
						"CANCELED",
						"ROLLBACK",
					),
				},
			},
		},
	}
}

type ScpTasksModel struct {
	Limit    types.Int64  `tfsdk:"limit"`
	Offset   types.Int64  `tfsdk:"offset"`
	Q        types.String `tfsdk:"q"`
	ScpTasks types.Set    `tfsdk:"scp_tasks"`
	ServerId types.Int64  `tfsdk:"server_id"`
	State    types.String `tfsdk:"state"`
}

var _ basetypes.ObjectTypable = ScpTasksType{}

type ScpTasksType struct {
	basetypes.ObjectType
}

func (t ScpTasksType) Equal(o attr.Type) bool {
	other, ok := o.(ScpTasksType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ScpTasksType) String() string {
	return "ScpTasksType"
}

func (t ScpTasksType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	executingUserAttribute, ok := attributes["executing_user"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`executing_user is missing from object`)

		return nil, diags
	}

	executingUserVal, ok := executingUserAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`executing_user expected to be basetypes.ObjectValue, was: %T`, executingUserAttribute))
	}

	finishedAtAttribute, ok := attributes["finished_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`finished_at is missing from object`)

		return nil, diags
	}

	finishedAtVal, ok := finishedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`finished_at expected to be basetypes.StringValue, was: %T`, finishedAtAttribute))
	}

	messageAttribute, ok := attributes["message"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`message is missing from object`)

		return nil, diags
	}

	messageVal, ok := messageAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`message expected to be basetypes.StringValue, was: %T`, messageAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	onRollbackAttribute, ok := attributes["on_rollback"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`on_rollback is missing from object`)

		return nil, diags
	}

	onRollbackVal, ok := onRollbackAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`on_rollback expected to be basetypes.BoolValue, was: %T`, onRollbackAttribute))
	}

	startedAtAttribute, ok := attributes["started_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`started_at is missing from object`)

		return nil, diags
	}

	startedAtVal, ok := startedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`started_at expected to be basetypes.StringValue, was: %T`, startedAtAttribute))
	}

	stateAttribute, ok := attributes["state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state is missing from object`)

		return nil, diags
	}

	stateVal, ok := stateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state expected to be basetypes.StringValue, was: %T`, stateAttribute))
	}

	taskProgressAttribute, ok := attributes["task_progress"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`task_progress is missing from object`)

		return nil, diags
	}

	taskProgressVal, ok := taskProgressAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`task_progress expected to be basetypes.ObjectValue, was: %T`, taskProgressAttribute))
	}

	uuidAttribute, ok := attributes["uuid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uuid is missing from object`)

		return nil, diags
	}

	uuidVal, ok := uuidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uuid expected to be basetypes.StringValue, was: %T`, uuidAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ScpTasksValue{
		ExecutingUser: executingUserVal,
		FinishedAt:    finishedAtVal,
		Message:       messageVal,
		Name:          nameVal,
		OnRollback:    onRollbackVal,
		StartedAt:     startedAtVal,
		State:         stateVal,
		TaskProgress:  taskProgressVal,
		Uuid:          uuidVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewScpTasksValueNull() ScpTasksValue {
	return ScpTasksValue{
		state: attr.ValueStateNull,
	}
}

func NewScpTasksValueUnknown() ScpTasksValue {
	return ScpTasksValue{
		state: attr.ValueStateUnknown,
	}
}

func NewScpTasksValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ScpTasksValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ScpTasksValue Attribute Value",
				"While creating a ScpTasksValue value, a missing attribute value was detected. "+
					"A ScpTasksValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScpTasksValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ScpTasksValue Attribute Type",
				"While creating a ScpTasksValue value, an invalid attribute value was detected. "+
					"A ScpTasksValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScpTasksValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ScpTasksValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ScpTasksValue Attribute Value",
				"While creating a ScpTasksValue value, an extra attribute value was detected. "+
					"A ScpTasksValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ScpTasksValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewScpTasksValueUnknown(), diags
	}

	executingUserAttribute, ok := attributes["executing_user"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`executing_user is missing from object`)

		return NewScpTasksValueUnknown(), diags
	}

	executingUserVal, ok := executingUserAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`executing_user expected to be basetypes.ObjectValue, was: %T`, executingUserAttribute))
	}

	finishedAtAttribute, ok := attributes["finished_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`finished_at is missing from object`)

		return NewScpTasksValueUnknown(), diags
	}

	finishedAtVal, ok := finishedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`finished_at expected to be basetypes.StringValue, was: %T`, finishedAtAttribute))
	}

	messageAttribute, ok := attributes["message"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`message is missing from object`)

		return NewScpTasksValueUnknown(), diags
	}

	messageVal, ok := messageAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`message expected to be basetypes.StringValue, was: %T`, messageAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewScpTasksValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	onRollbackAttribute, ok := attributes["on_rollback"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`on_rollback is missing from object`)

		return NewScpTasksValueUnknown(), diags
	}

	onRollbackVal, ok := onRollbackAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`on_rollback expected to be basetypes.BoolValue, was: %T`, onRollbackAttribute))
	}

	startedAtAttribute, ok := attributes["started_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`started_at is missing from object`)

		return NewScpTasksValueUnknown(), diags
	}

	startedAtVal, ok := startedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`started_at expected to be basetypes.StringValue, was: %T`, startedAtAttribute))
	}

	stateAttribute, ok := attributes["state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state is missing from object`)

		return NewScpTasksValueUnknown(), diags
	}

	stateVal, ok := stateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state expected to be basetypes.StringValue, was: %T`, stateAttribute))
	}

	taskProgressAttribute, ok := attributes["task_progress"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`task_progress is missing from object`)

		return NewScpTasksValueUnknown(), diags
	}

	taskProgressVal, ok := taskProgressAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`task_progress expected to be basetypes.ObjectValue, was: %T`, taskProgressAttribute))
	}

	uuidAttribute, ok := attributes["uuid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uuid is missing from object`)

		return NewScpTasksValueUnknown(), diags
	}

	uuidVal, ok := uuidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uuid expected to be basetypes.StringValue, was: %T`, uuidAttribute))
	}

	if diags.HasError() {
		return NewScpTasksValueUnknown(), diags
	}

	return ScpTasksValue{
		ExecutingUser: executingUserVal,
		FinishedAt:    finishedAtVal,
		Message:       messageVal,
		Name:          nameVal,
		OnRollback:    onRollbackVal,
		StartedAt:     startedAtVal,
		State:         stateVal,
		TaskProgress:  taskProgressVal,
		Uuid:          uuidVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewScpTasksValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ScpTasksValue {
	object, diags := NewScpTasksValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewScpTasksValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ScpTasksType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewScpTasksValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewScpTasksValueUnknown(), nil
	}

	if in.IsNull() {
		return NewScpTasksValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewScpTasksValueMust(ScpTasksValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ScpTasksType) ValueType(ctx context.Context) attr.Value {
	return ScpTasksValue{}
}

var _ basetypes.ObjectValuable = ScpTasksValue{}

type ScpTasksValue struct {
	ExecutingUser basetypes.ObjectValue `tfsdk:"executing_user"`
	FinishedAt    basetypes.StringValue `tfsdk:"finished_at"`
	Message       basetypes.StringValue `tfsdk:"message"`
	Name          basetypes.StringValue `tfsdk:"name"`
	OnRollback    basetypes.BoolValue   `tfsdk:"on_rollback"`
	StartedAt     basetypes.StringValue `tfsdk:"started_at"`
	State         basetypes.StringValue `tfsdk:"state"`
	TaskProgress  basetypes.ObjectValue `tfsdk:"task_progress"`
	Uuid          basetypes.StringValue `tfsdk:"uuid"`
	state         attr.ValueState
}

func (v ScpTasksValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 9)

	var val tftypes.Value
	var err error

	attrTypes["executing_user"] = basetypes.ObjectType{
		AttrTypes: ExecutingUserValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["finished_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["message"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["on_rollback"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["started_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["state"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["task_progress"] = basetypes.ObjectType{
		AttrTypes: TaskProgressValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["uuid"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 9)

		val, err = v.ExecutingUser.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["executing_user"] = val

		val, err = v.FinishedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["finished_at"] = val

		val, err = v.Message.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["message"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.OnRollback.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["on_rollback"] = val

		val, err = v.StartedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["started_at"] = val

		val, err = v.State.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["state"] = val

		val, err = v.TaskProgress.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["task_progress"] = val

		val, err = v.Uuid.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["uuid"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ScpTasksValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ScpTasksValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ScpTasksValue) String() string {
	return "ScpTasksValue"
}

func (v ScpTasksValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var executingUser basetypes.ObjectValue

	if v.ExecutingUser.IsNull() {
		executingUser = types.ObjectNull(
			ExecutingUserValue{}.AttributeTypes(ctx),
		)
	}

	if v.ExecutingUser.IsUnknown() {
		executingUser = types.ObjectUnknown(
			ExecutingUserValue{}.AttributeTypes(ctx),
		)
	}

	if !v.ExecutingUser.IsNull() && !v.ExecutingUser.IsUnknown() {
		executingUser = types.ObjectValueMust(
			ExecutingUserValue{}.AttributeTypes(ctx),
			v.ExecutingUser.Attributes(),
		)
	}

	var taskProgress basetypes.ObjectValue

	if v.TaskProgress.IsNull() {
		taskProgress = types.ObjectNull(
			TaskProgressValue{}.AttributeTypes(ctx),
		)
	}

	if v.TaskProgress.IsUnknown() {
		taskProgress = types.ObjectUnknown(
			TaskProgressValue{}.AttributeTypes(ctx),
		)
	}

	if !v.TaskProgress.IsNull() && !v.TaskProgress.IsUnknown() {
		taskProgress = types.ObjectValueMust(
			TaskProgressValue{}.AttributeTypes(ctx),
			v.TaskProgress.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"executing_user": basetypes.ObjectType{
			AttrTypes: ExecutingUserValue{}.AttributeTypes(ctx),
		},
		"finished_at": basetypes.StringType{},
		"message":     basetypes.StringType{},
		"name":        basetypes.StringType{},
		"on_rollback": basetypes.BoolType{},
		"started_at":  basetypes.StringType{},
		"state":       basetypes.StringType{},
		"task_progress": basetypes.ObjectType{
			AttrTypes: TaskProgressValue{}.AttributeTypes(ctx),
		},
		"uuid": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"executing_user": executingUser,
			"finished_at":    v.FinishedAt,
			"message":        v.Message,
			"name":           v.Name,
			"on_rollback":    v.OnRollback,
			"started_at":     v.StartedAt,
			"state":          v.State,
			"task_progress":  taskProgress,
			"uuid":           v.Uuid,
		})

	return objVal, diags
}

func (v ScpTasksValue) Equal(o attr.Value) bool {
	other, ok := o.(ScpTasksValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ExecutingUser.Equal(other.ExecutingUser) {
		return false
	}

	if !v.FinishedAt.Equal(other.FinishedAt) {
		return false
	}

	if !v.Message.Equal(other.Message) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.OnRollback.Equal(other.OnRollback) {
		return false
	}

	if !v.StartedAt.Equal(other.StartedAt) {
		return false
	}

	if !v.State.Equal(other.State) {
		return false
	}

	if !v.TaskProgress.Equal(other.TaskProgress) {
		return false
	}

	if !v.Uuid.Equal(other.Uuid) {
		return false
	}

	return true
}

func (v ScpTasksValue) Type(ctx context.Context) attr.Type {
	return ScpTasksType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ScpTasksValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"executing_user": basetypes.ObjectType{
			AttrTypes: ExecutingUserValue{}.AttributeTypes(ctx),
		},
		"finished_at": basetypes.StringType{},
		"message":     basetypes.StringType{},
		"name":        basetypes.StringType{},
		"on_rollback": basetypes.BoolType{},
		"started_at":  basetypes.StringType{},
		"state":       basetypes.StringType{},
		"task_progress": basetypes.ObjectType{
			AttrTypes: TaskProgressValue{}.AttributeTypes(ctx),
		},
		"uuid": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ExecutingUserType{}

type ExecutingUserType struct {
	basetypes.ObjectType
}

func (t ExecutingUserType) Equal(o attr.Type) bool {
	other, ok := o.(ExecutingUserType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ExecutingUserType) String() string {
	return "ExecutingUserType"
}

func (t ExecutingUserType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	companyAttribute, ok := attributes["company"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`company is missing from object`)

		return nil, diags
	}

	companyVal, ok := companyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`company expected to be basetypes.StringValue, was: %T`, companyAttribute))
	}

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return nil, diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	firstnameAttribute, ok := attributes["firstname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`firstname is missing from object`)

		return nil, diags
	}

	firstnameVal, ok := firstnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`firstname expected to be basetypes.StringValue, was: %T`, firstnameAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	lastnameAttribute, ok := attributes["lastname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`lastname is missing from object`)

		return nil, diags
	}

	lastnameVal, ok := lastnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`lastname expected to be basetypes.StringValue, was: %T`, lastnameAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return nil, diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ExecutingUserValue{
		Company:   companyVal,
		Email:     emailVal,
		Firstname: firstnameVal,
		Id:        idVal,
		Lastname:  lastnameVal,
		Username:  usernameVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewExecutingUserValueNull() ExecutingUserValue {
	return ExecutingUserValue{
		state: attr.ValueStateNull,
	}
}

func NewExecutingUserValueUnknown() ExecutingUserValue {
	return ExecutingUserValue{
		state: attr.ValueStateUnknown,
	}
}

func NewExecutingUserValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ExecutingUserValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ExecutingUserValue Attribute Value",
				"While creating a ExecutingUserValue value, a missing attribute value was detected. "+
					"A ExecutingUserValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ExecutingUserValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ExecutingUserValue Attribute Type",
				"While creating a ExecutingUserValue value, an invalid attribute value was detected. "+
					"A ExecutingUserValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ExecutingUserValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ExecutingUserValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ExecutingUserValue Attribute Value",
				"While creating a ExecutingUserValue value, an extra attribute value was detected. "+
					"A ExecutingUserValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ExecutingUserValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewExecutingUserValueUnknown(), diags
	}

	companyAttribute, ok := attributes["company"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`company is missing from object`)

		return NewExecutingUserValueUnknown(), diags
	}

	companyVal, ok := companyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`company expected to be basetypes.StringValue, was: %T`, companyAttribute))
	}

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return NewExecutingUserValueUnknown(), diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	firstnameAttribute, ok := attributes["firstname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`firstname is missing from object`)

		return NewExecutingUserValueUnknown(), diags
	}

	firstnameVal, ok := firstnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`firstname expected to be basetypes.StringValue, was: %T`, firstnameAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewExecutingUserValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	lastnameAttribute, ok := attributes["lastname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`lastname is missing from object`)

		return NewExecutingUserValueUnknown(), diags
	}

	lastnameVal, ok := lastnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`lastname expected to be basetypes.StringValue, was: %T`, lastnameAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return NewExecutingUserValueUnknown(), diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	if diags.HasError() {
		return NewExecutingUserValueUnknown(), diags
	}

	return ExecutingUserValue{
		Company:   companyVal,
		Email:     emailVal,
		Firstname: firstnameVal,
		Id:        idVal,
		Lastname:  lastnameVal,
		Username:  usernameVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewExecutingUserValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ExecutingUserValue {
	object, diags := NewExecutingUserValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewExecutingUserValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ExecutingUserType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewExecutingUserValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewExecutingUserValueUnknown(), nil
	}

	if in.IsNull() {
		return NewExecutingUserValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewExecutingUserValueMust(ExecutingUserValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ExecutingUserType) ValueType(ctx context.Context) attr.Value {
	return ExecutingUserValue{}
}

var _ basetypes.ObjectValuable = ExecutingUserValue{}

type ExecutingUserValue struct {
	Company   basetypes.StringValue `tfsdk:"company"`
	Email     basetypes.StringValue `tfsdk:"email"`
	Firstname basetypes.StringValue `tfsdk:"firstname"`
	Id        basetypes.Int64Value  `tfsdk:"id"`
	Lastname  basetypes.StringValue `tfsdk:"lastname"`
	Username  basetypes.StringValue `tfsdk:"username"`
	state     attr.ValueState
}

func (v ExecutingUserValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["company"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["email"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["firstname"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["lastname"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["username"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.Company.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["company"] = val

		val, err = v.Email.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["email"] = val

		val, err = v.Firstname.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["firstname"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Lastname.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["lastname"] = val

		val, err = v.Username.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["username"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ExecutingUserValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ExecutingUserValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ExecutingUserValue) String() string {
	return "ExecutingUserValue"
}

func (v ExecutingUserValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"company":   basetypes.StringType{},
		"email":     basetypes.StringType{},
		"firstname": basetypes.StringType{},
		"id":        basetypes.Int64Type{},
		"lastname":  basetypes.StringType{},
		"username":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"company":   v.Company,
			"email":     v.Email,
			"firstname": v.Firstname,
			"id":        v.Id,
			"lastname":  v.Lastname,
			"username":  v.Username,
		})

	return objVal, diags
}

func (v ExecutingUserValue) Equal(o attr.Value) bool {
	other, ok := o.(ExecutingUserValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Company.Equal(other.Company) {
		return false
	}

	if !v.Email.Equal(other.Email) {
		return false
	}

	if !v.Firstname.Equal(other.Firstname) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Lastname.Equal(other.Lastname) {
		return false
	}

	if !v.Username.Equal(other.Username) {
		return false
	}

	return true
}

func (v ExecutingUserValue) Type(ctx context.Context) attr.Type {
	return ExecutingUserType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ExecutingUserValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"company":   basetypes.StringType{},
		"email":     basetypes.StringType{},
		"firstname": basetypes.StringType{},
		"id":        basetypes.Int64Type{},
		"lastname":  basetypes.StringType{},
		"username":  basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = TaskProgressType{}

type TaskProgressType struct {
	basetypes.ObjectType
}

func (t TaskProgressType) Equal(o attr.Type) bool {
	other, ok := o.(TaskProgressType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TaskProgressType) String() string {
	return "TaskProgressType"
}

func (t TaskProgressType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	expectedFinishedAtAttribute, ok := attributes["expected_finished_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`expected_finished_at is missing from object`)

		return nil, diags
	}

	expectedFinishedAtVal, ok := expectedFinishedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`expected_finished_at expected to be basetypes.StringValue, was: %T`, expectedFinishedAtAttribute))
	}

	progressInPercentAttribute, ok := attributes["progress_in_percent"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`progress_in_percent is missing from object`)

		return nil, diags
	}

	progressInPercentVal, ok := progressInPercentAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`progress_in_percent expected to be basetypes.Float64Value, was: %T`, progressInPercentAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TaskProgressValue{
		ExpectedFinishedAt: expectedFinishedAtVal,
		ProgressInPercent:  progressInPercentVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewTaskProgressValueNull() TaskProgressValue {
	return TaskProgressValue{
		state: attr.ValueStateNull,
	}
}

func NewTaskProgressValueUnknown() TaskProgressValue {
	return TaskProgressValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTaskProgressValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TaskProgressValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TaskProgressValue Attribute Value",
				"While creating a TaskProgressValue value, a missing attribute value was detected. "+
					"A TaskProgressValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TaskProgressValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TaskProgressValue Attribute Type",
				"While creating a TaskProgressValue value, an invalid attribute value was detected. "+
					"A TaskProgressValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TaskProgressValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TaskProgressValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TaskProgressValue Attribute Value",
				"While creating a TaskProgressValue value, an extra attribute value was detected. "+
					"A TaskProgressValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TaskProgressValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTaskProgressValueUnknown(), diags
	}

	expectedFinishedAtAttribute, ok := attributes["expected_finished_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`expected_finished_at is missing from object`)

		return NewTaskProgressValueUnknown(), diags
	}

	expectedFinishedAtVal, ok := expectedFinishedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`expected_finished_at expected to be basetypes.StringValue, was: %T`, expectedFinishedAtAttribute))
	}

	progressInPercentAttribute, ok := attributes["progress_in_percent"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`progress_in_percent is missing from object`)

		return NewTaskProgressValueUnknown(), diags
	}

	progressInPercentVal, ok := progressInPercentAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`progress_in_percent expected to be basetypes.Float64Value, was: %T`, progressInPercentAttribute))
	}

	if diags.HasError() {
		return NewTaskProgressValueUnknown(), diags
	}

	return TaskProgressValue{
		ExpectedFinishedAt: expectedFinishedAtVal,
		ProgressInPercent:  progressInPercentVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewTaskProgressValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TaskProgressValue {
	object, diags := NewTaskProgressValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTaskProgressValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TaskProgressType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTaskProgressValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTaskProgressValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTaskProgressValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTaskProgressValueMust(TaskProgressValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TaskProgressType) ValueType(ctx context.Context) attr.Value {
	return TaskProgressValue{}
}

var _ basetypes.ObjectValuable = TaskProgressValue{}

type TaskProgressValue struct {
	ExpectedFinishedAt basetypes.StringValue  `tfsdk:"expected_finished_at"`
	ProgressInPercent  basetypes.Float64Value `tfsdk:"progress_in_percent"`
	state              attr.ValueState
}

func (v TaskProgressValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["expected_finished_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["progress_in_percent"] = basetypes.Float64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.ExpectedFinishedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["expected_finished_at"] = val

		val, err = v.ProgressInPercent.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["progress_in_percent"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TaskProgressValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TaskProgressValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TaskProgressValue) String() string {
	return "TaskProgressValue"
}

func (v TaskProgressValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"expected_finished_at": basetypes.StringType{},
		"progress_in_percent":  basetypes.Float64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"expected_finished_at": v.ExpectedFinishedAt,
			"progress_in_percent":  v.ProgressInPercent,
		})

	return objVal, diags
}

func (v TaskProgressValue) Equal(o attr.Value) bool {
	other, ok := o.(TaskProgressValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ExpectedFinishedAt.Equal(other.ExpectedFinishedAt) {
		return false
	}

	if !v.ProgressInPercent.Equal(other.ProgressInPercent) {
		return false
	}

	return true
}

func (v TaskProgressValue) Type(ctx context.Context) attr.Type {
	return TaskProgressType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TaskProgressValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"expected_finished_at": basetypes.StringType{},
		"progress_in_percent":  basetypes.Float64Type{},
	}
}
