// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scprdnsipv4

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpRdnsIpv4DataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"), ""),
				},
			},
			"rdns": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type ScpRdnsIpv4Model struct {
	Ip   types.String `tfsdk:"ip"`
	Rdns types.String `tfsdk:"rdns"`
}
