// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scpserverdisksupporteddrivers

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpServerDiskSupportedDriversDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		MarkdownDescription: "Get a list of supported storage drivers for this server",
		Attributes: map[string]schema.Attribute{
			"scp_server_disk_supported_drivers": schema.SetAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"server_id": schema.Int64Attribute{
				Required: true,
			},
		},
	}
}

type ScpServerDiskSupportedDriversModel struct {
	ScpServerDiskSupportedDrivers types.Set   `tfsdk:"scp_server_disk_supported_drivers"`
	ServerId                      types.Int64 `tfsdk:"server_id"`
}
