// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scpservers

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpServersDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"firewall_policy_id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Filter by assigned firewall policy",
				MarkdownDescription: "Filter by assigned firewall policy",
			},
			"ip": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Filter by ip",
				MarkdownDescription: "Filter by ip",
			},
			"limit": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				Validators: []validator.Int64{
					int64validator.Between(0, 2147483647),
				},
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Filter by server name",
				MarkdownDescription: "Filter by server name",
			},
			"offset": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				Validators: []validator.Int64{
					int64validator.Between(0, 2147483647),
				},
			},
			"q": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Search ignoring case within the property name, nickname, or ipv4Addresses",
				MarkdownDescription: "Search ignoring case within the property name, nickname, or ipv4Addresses",
			},
			"scp_servers": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"disabled": schema.BoolAttribute{
							Computed: true,
						},
						"hostname": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.Int64Attribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"nickname": schema.StringAttribute{
							Computed: true,
						},
						"template": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"id": schema.Int64Attribute{
									Computed: true,
								},
								"name": schema.StringAttribute{
									Computed: true,
								},
							},
							CustomType: TemplateType{
								ObjectType: types.ObjectType{
									AttrTypes: TemplateValue{}.AttributeTypes(ctx),
								},
							},
							Computed: true,
						},
					},
					CustomType: ScpServersType{
						ObjectType: types.ObjectType{
							AttrTypes: ScpServersValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"sort": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Sort by one or more fields. Prefix a field with '-' for descending order, no prefix for ascending. Allowed fields: name, nickname. Repeat the parameter to sort by multiple fields, e.g. ?sort=name&sort=-nickname.",
				MarkdownDescription: "Sort by one or more fields. Prefix a field with '-' for descending order, no prefix for ascending. Allowed fields: name, nickname. Repeat the parameter to sort by multiple fields, e.g. ?sort=name&sort=-nickname.",
			},
		},
	}
}

type ScpServersModel struct {
	FirewallPolicyId types.Int64  `tfsdk:"firewall_policy_id"`
	Ip               types.String `tfsdk:"ip"`
	Limit            types.Int64  `tfsdk:"limit"`
	Name             types.String `tfsdk:"name"`
	Offset           types.Int64  `tfsdk:"offset"`
	Q                types.String `tfsdk:"q"`
	ScpServers       types.Set    `tfsdk:"scp_servers"`
	Sort             types.List   `tfsdk:"sort"`
}

var _ basetypes.ObjectTypable = ScpServersType{}

type ScpServersType struct {
	basetypes.ObjectType
}

func (t ScpServersType) Equal(o attr.Type) bool {
	other, ok := o.(ScpServersType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ScpServersType) String() string {
	return "ScpServersType"
}

func (t ScpServersType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	disabledAttribute, ok := attributes["disabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`disabled is missing from object`)

		return nil, diags
	}

	disabledVal, ok := disabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`disabled expected to be basetypes.BoolValue, was: %T`, disabledAttribute))
	}

	hostnameAttribute, ok := attributes["hostname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`hostname is missing from object`)

		return nil, diags
	}

	hostnameVal, ok := hostnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`hostname expected to be basetypes.StringValue, was: %T`, hostnameAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	nicknameAttribute, ok := attributes["nickname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`nickname is missing from object`)

		return nil, diags
	}

	nicknameVal, ok := nicknameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`nickname expected to be basetypes.StringValue, was: %T`, nicknameAttribute))
	}

	templateAttribute, ok := attributes["template"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`template is missing from object`)

		return nil, diags
	}

	templateVal, ok := templateAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`template expected to be basetypes.ObjectValue, was: %T`, templateAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ScpServersValue{
		Disabled: disabledVal,
		Hostname: hostnameVal,
		Id:       idVal,
		Name:     nameVal,
		Nickname: nicknameVal,
		Template: templateVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewScpServersValueNull() ScpServersValue {
	return ScpServersValue{
		state: attr.ValueStateNull,
	}
}

func NewScpServersValueUnknown() ScpServersValue {
	return ScpServersValue{
		state: attr.ValueStateUnknown,
	}
}

func NewScpServersValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ScpServersValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ScpServersValue Attribute Value",
				"While creating a ScpServersValue value, a missing attribute value was detected. "+
					"A ScpServersValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScpServersValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ScpServersValue Attribute Type",
				"While creating a ScpServersValue value, an invalid attribute value was detected. "+
					"A ScpServersValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScpServersValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ScpServersValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ScpServersValue Attribute Value",
				"While creating a ScpServersValue value, an extra attribute value was detected. "+
					"A ScpServersValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ScpServersValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewScpServersValueUnknown(), diags
	}

	disabledAttribute, ok := attributes["disabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`disabled is missing from object`)

		return NewScpServersValueUnknown(), diags
	}

	disabledVal, ok := disabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`disabled expected to be basetypes.BoolValue, was: %T`, disabledAttribute))
	}

	hostnameAttribute, ok := attributes["hostname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`hostname is missing from object`)

		return NewScpServersValueUnknown(), diags
	}

	hostnameVal, ok := hostnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`hostname expected to be basetypes.StringValue, was: %T`, hostnameAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewScpServersValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewScpServersValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	nicknameAttribute, ok := attributes["nickname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`nickname is missing from object`)

		return NewScpServersValueUnknown(), diags
	}

	nicknameVal, ok := nicknameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`nickname expected to be basetypes.StringValue, was: %T`, nicknameAttribute))
	}

	templateAttribute, ok := attributes["template"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`template is missing from object`)

		return NewScpServersValueUnknown(), diags
	}

	templateVal, ok := templateAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`template expected to be basetypes.ObjectValue, was: %T`, templateAttribute))
	}

	if diags.HasError() {
		return NewScpServersValueUnknown(), diags
	}

	return ScpServersValue{
		Disabled: disabledVal,
		Hostname: hostnameVal,
		Id:       idVal,
		Name:     nameVal,
		Nickname: nicknameVal,
		Template: templateVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewScpServersValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ScpServersValue {
	object, diags := NewScpServersValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewScpServersValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ScpServersType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewScpServersValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewScpServersValueUnknown(), nil
	}

	if in.IsNull() {
		return NewScpServersValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewScpServersValueMust(ScpServersValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ScpServersType) ValueType(ctx context.Context) attr.Value {
	return ScpServersValue{}
}

var _ basetypes.ObjectValuable = ScpServersValue{}

type ScpServersValue struct {
	Disabled basetypes.BoolValue   `tfsdk:"disabled"`
	Hostname basetypes.StringValue `tfsdk:"hostname"`
	Id       basetypes.Int64Value  `tfsdk:"id"`
	Name     basetypes.StringValue `tfsdk:"name"`
	Nickname basetypes.StringValue `tfsdk:"nickname"`
	Template basetypes.ObjectValue `tfsdk:"template"`
	state    attr.ValueState
}

func (v ScpServersValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["disabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["hostname"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["nickname"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["template"] = basetypes.ObjectType{
		AttrTypes: TemplateValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.Disabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["disabled"] = val

		val, err = v.Hostname.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["hostname"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Nickname.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["nickname"] = val

		val, err = v.Template.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["template"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ScpServersValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ScpServersValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ScpServersValue) String() string {
	return "ScpServersValue"
}

func (v ScpServersValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var template basetypes.ObjectValue

	if v.Template.IsNull() {
		template = types.ObjectNull(
			TemplateValue{}.AttributeTypes(ctx),
		)
	}

	if v.Template.IsUnknown() {
		template = types.ObjectUnknown(
			TemplateValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Template.IsNull() && !v.Template.IsUnknown() {
		template = types.ObjectValueMust(
			TemplateValue{}.AttributeTypes(ctx),
			v.Template.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"disabled": basetypes.BoolType{},
		"hostname": basetypes.StringType{},
		"id":       basetypes.Int64Type{},
		"name":     basetypes.StringType{},
		"nickname": basetypes.StringType{},
		"template": basetypes.ObjectType{
			AttrTypes: TemplateValue{}.AttributeTypes(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"disabled": v.Disabled,
			"hostname": v.Hostname,
			"id":       v.Id,
			"name":     v.Name,
			"nickname": v.Nickname,
			"template": template,
		})

	return objVal, diags
}

func (v ScpServersValue) Equal(o attr.Value) bool {
	other, ok := o.(ScpServersValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Disabled.Equal(other.Disabled) {
		return false
	}

	if !v.Hostname.Equal(other.Hostname) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Nickname.Equal(other.Nickname) {
		return false
	}

	if !v.Template.Equal(other.Template) {
		return false
	}

	return true
}

func (v ScpServersValue) Type(ctx context.Context) attr.Type {
	return ScpServersType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ScpServersValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"disabled": basetypes.BoolType{},
		"hostname": basetypes.StringType{},
		"id":       basetypes.Int64Type{},
		"name":     basetypes.StringType{},
		"nickname": basetypes.StringType{},
		"template": basetypes.ObjectType{
			AttrTypes: TemplateValue{}.AttributeTypes(ctx),
		},
	}
}

var _ basetypes.ObjectTypable = TemplateType{}

type TemplateType struct {
	basetypes.ObjectType
}

func (t TemplateType) Equal(o attr.Type) bool {
	other, ok := o.(TemplateType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TemplateType) String() string {
	return "TemplateType"
}

func (t TemplateType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TemplateValue{
		Id:    idVal,
		Name:  nameVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewTemplateValueNull() TemplateValue {
	return TemplateValue{
		state: attr.ValueStateNull,
	}
}

func NewTemplateValueUnknown() TemplateValue {
	return TemplateValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTemplateValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TemplateValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TemplateValue Attribute Value",
				"While creating a TemplateValue value, a missing attribute value was detected. "+
					"A TemplateValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TemplateValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TemplateValue Attribute Type",
				"While creating a TemplateValue value, an invalid attribute value was detected. "+
					"A TemplateValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TemplateValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TemplateValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TemplateValue Attribute Value",
				"While creating a TemplateValue value, an extra attribute value was detected. "+
					"A TemplateValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TemplateValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTemplateValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewTemplateValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewTemplateValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return NewTemplateValueUnknown(), diags
	}

	return TemplateValue{
		Id:    idVal,
		Name:  nameVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewTemplateValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TemplateValue {
	object, diags := NewTemplateValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTemplateValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TemplateType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTemplateValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTemplateValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTemplateValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTemplateValueMust(TemplateValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TemplateType) ValueType(ctx context.Context) attr.Value {
	return TemplateValue{}
}

var _ basetypes.ObjectValuable = TemplateValue{}

type TemplateValue struct {
	Id    basetypes.Int64Value  `tfsdk:"id"`
	Name  basetypes.StringValue `tfsdk:"name"`
	state attr.ValueState
}

func (v TemplateValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TemplateValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TemplateValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TemplateValue) String() string {
	return "TemplateValue"
}

func (v TemplateValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":   basetypes.Int64Type{},
		"name": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":   v.Id,
			"name": v.Name,
		})

	return objVal, diags
}

func (v TemplateValue) Equal(o attr.Value) bool {
	other, ok := o.(TemplateValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	return true
}

func (v TemplateValue) Type(ctx context.Context) attr.Type {
	return TemplateType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TemplateValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.Int64Type{},
		"name": basetypes.StringType{},
	}
}
