// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scpuserfailoveripsv6

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpUserFailoveripsV6DataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"scp_user_failoverips_v6": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"editable": schema.BoolAttribute{
							Computed: true,
						},
						"id": schema.Int64Attribute{
							Computed: true,
						},
						"network_prefix": schema.StringAttribute{
							Computed: true,
						},
						"network_prefix_length": schema.Int64Attribute{
							Computed: true,
						},
						"server": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"id": schema.Int64Attribute{
									Computed: true,
								},
								"name": schema.StringAttribute{
									Computed: true,
								},
							},
							CustomType: ServerType{
								ObjectType: types.ObjectType{
									AttrTypes: ServerValue{}.AttributeTypes(ctx),
								},
							},
							Computed: true,
						},
						"site": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"city": schema.StringAttribute{
									Computed: true,
								},
								"id": schema.Int64Attribute{
									Computed: true,
								},
							},
							CustomType: SiteType{
								ObjectType: types.ObjectType{
									AttrTypes: SiteValue{}.AttributeTypes(ctx),
								},
							},
							Computed: true,
						},
						"user": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"company": schema.StringAttribute{
									Computed: true,
								},
								"email": schema.StringAttribute{
									Computed: true,
								},
								"firstname": schema.StringAttribute{
									Computed: true,
								},
								"id": schema.Int64Attribute{
									Computed: true,
								},
								"lastname": schema.StringAttribute{
									Computed: true,
								},
								"username": schema.StringAttribute{
									Computed: true,
								},
							},
							CustomType: UserType{
								ObjectType: types.ObjectType{
									AttrTypes: UserValue{}.AttributeTypes(ctx),
								},
							},
							Computed: true,
						},
					},
					CustomType: ScpUserFailoveripsV6Type{
						ObjectType: types.ObjectType{
							AttrTypes: ScpUserFailoveripsV6Value{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"server_id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Filter failover IPv6s of this user by server id",
				MarkdownDescription: "Filter failover IPv6s of this user by server id",
			},
			"user_id": schema.Int64Attribute{
				Required: true,
			},
		},
	}
}

type ScpUserFailoveripsV6Model struct {
	Ip                   types.String `tfsdk:"ip"`
	ScpUserFailoveripsV6 types.Set    `tfsdk:"scp_user_failoverips_v6"`
	ServerId             types.Int64  `tfsdk:"server_id"`
	UserId               types.Int64  `tfsdk:"user_id"`
}

var _ basetypes.ObjectTypable = ScpUserFailoveripsV6Type{}

type ScpUserFailoveripsV6Type struct {
	basetypes.ObjectType
}

func (t ScpUserFailoveripsV6Type) Equal(o attr.Type) bool {
	other, ok := o.(ScpUserFailoveripsV6Type)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ScpUserFailoveripsV6Type) String() string {
	return "ScpUserFailoveripsV6Type"
}

func (t ScpUserFailoveripsV6Type) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	editableAttribute, ok := attributes["editable"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`editable is missing from object`)

		return nil, diags
	}

	editableVal, ok := editableAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`editable expected to be basetypes.BoolValue, was: %T`, editableAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	networkPrefixAttribute, ok := attributes["network_prefix"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`network_prefix is missing from object`)

		return nil, diags
	}

	networkPrefixVal, ok := networkPrefixAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`network_prefix expected to be basetypes.StringValue, was: %T`, networkPrefixAttribute))
	}

	networkPrefixLengthAttribute, ok := attributes["network_prefix_length"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`network_prefix_length is missing from object`)

		return nil, diags
	}

	networkPrefixLengthVal, ok := networkPrefixLengthAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`network_prefix_length expected to be basetypes.Int64Value, was: %T`, networkPrefixLengthAttribute))
	}

	serverAttribute, ok := attributes["server"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`server is missing from object`)

		return nil, diags
	}

	serverVal, ok := serverAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`server expected to be basetypes.ObjectValue, was: %T`, serverAttribute))
	}

	siteAttribute, ok := attributes["site"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`site is missing from object`)

		return nil, diags
	}

	siteVal, ok := siteAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`site expected to be basetypes.ObjectValue, was: %T`, siteAttribute))
	}

	userAttribute, ok := attributes["user"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user is missing from object`)

		return nil, diags
	}

	userVal, ok := userAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user expected to be basetypes.ObjectValue, was: %T`, userAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ScpUserFailoveripsV6Value{
		Editable:            editableVal,
		Id:                  idVal,
		NetworkPrefix:       networkPrefixVal,
		NetworkPrefixLength: networkPrefixLengthVal,
		Server:              serverVal,
		Site:                siteVal,
		User:                userVal,
		state:               attr.ValueStateKnown,
	}, diags
}

func NewScpUserFailoveripsV6ValueNull() ScpUserFailoveripsV6Value {
	return ScpUserFailoveripsV6Value{
		state: attr.ValueStateNull,
	}
}

func NewScpUserFailoveripsV6ValueUnknown() ScpUserFailoveripsV6Value {
	return ScpUserFailoveripsV6Value{
		state: attr.ValueStateUnknown,
	}
}

func NewScpUserFailoveripsV6Value(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ScpUserFailoveripsV6Value, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ScpUserFailoveripsV6Value Attribute Value",
				"While creating a ScpUserFailoveripsV6Value value, a missing attribute value was detected. "+
					"A ScpUserFailoveripsV6Value must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScpUserFailoveripsV6Value Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ScpUserFailoveripsV6Value Attribute Type",
				"While creating a ScpUserFailoveripsV6Value value, an invalid attribute value was detected. "+
					"A ScpUserFailoveripsV6Value must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScpUserFailoveripsV6Value Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ScpUserFailoveripsV6Value Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ScpUserFailoveripsV6Value Attribute Value",
				"While creating a ScpUserFailoveripsV6Value value, an extra attribute value was detected. "+
					"A ScpUserFailoveripsV6Value must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ScpUserFailoveripsV6Value Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewScpUserFailoveripsV6ValueUnknown(), diags
	}

	editableAttribute, ok := attributes["editable"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`editable is missing from object`)

		return NewScpUserFailoveripsV6ValueUnknown(), diags
	}

	editableVal, ok := editableAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`editable expected to be basetypes.BoolValue, was: %T`, editableAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewScpUserFailoveripsV6ValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	networkPrefixAttribute, ok := attributes["network_prefix"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`network_prefix is missing from object`)

		return NewScpUserFailoveripsV6ValueUnknown(), diags
	}

	networkPrefixVal, ok := networkPrefixAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`network_prefix expected to be basetypes.StringValue, was: %T`, networkPrefixAttribute))
	}

	networkPrefixLengthAttribute, ok := attributes["network_prefix_length"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`network_prefix_length is missing from object`)

		return NewScpUserFailoveripsV6ValueUnknown(), diags
	}

	networkPrefixLengthVal, ok := networkPrefixLengthAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`network_prefix_length expected to be basetypes.Int64Value, was: %T`, networkPrefixLengthAttribute))
	}

	serverAttribute, ok := attributes["server"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`server is missing from object`)

		return NewScpUserFailoveripsV6ValueUnknown(), diags
	}

	serverVal, ok := serverAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`server expected to be basetypes.ObjectValue, was: %T`, serverAttribute))
	}

	siteAttribute, ok := attributes["site"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`site is missing from object`)

		return NewScpUserFailoveripsV6ValueUnknown(), diags
	}

	siteVal, ok := siteAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`site expected to be basetypes.ObjectValue, was: %T`, siteAttribute))
	}

	userAttribute, ok := attributes["user"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user is missing from object`)

		return NewScpUserFailoveripsV6ValueUnknown(), diags
	}

	userVal, ok := userAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user expected to be basetypes.ObjectValue, was: %T`, userAttribute))
	}

	if diags.HasError() {
		return NewScpUserFailoveripsV6ValueUnknown(), diags
	}

	return ScpUserFailoveripsV6Value{
		Editable:            editableVal,
		Id:                  idVal,
		NetworkPrefix:       networkPrefixVal,
		NetworkPrefixLength: networkPrefixLengthVal,
		Server:              serverVal,
		Site:                siteVal,
		User:                userVal,
		state:               attr.ValueStateKnown,
	}, diags
}

func NewScpUserFailoveripsV6ValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ScpUserFailoveripsV6Value {
	object, diags := NewScpUserFailoveripsV6Value(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewScpUserFailoveripsV6ValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ScpUserFailoveripsV6Type) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewScpUserFailoveripsV6ValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewScpUserFailoveripsV6ValueUnknown(), nil
	}

	if in.IsNull() {
		return NewScpUserFailoveripsV6ValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewScpUserFailoveripsV6ValueMust(ScpUserFailoveripsV6Value{}.AttributeTypes(ctx), attributes), nil
}

func (t ScpUserFailoveripsV6Type) ValueType(ctx context.Context) attr.Value {
	return ScpUserFailoveripsV6Value{}
}

var _ basetypes.ObjectValuable = ScpUserFailoveripsV6Value{}

type ScpUserFailoveripsV6Value struct {
	Editable            basetypes.BoolValue   `tfsdk:"editable"`
	Id                  basetypes.Int64Value  `tfsdk:"id"`
	NetworkPrefix       basetypes.StringValue `tfsdk:"network_prefix"`
	NetworkPrefixLength basetypes.Int64Value  `tfsdk:"network_prefix_length"`
	Server              basetypes.ObjectValue `tfsdk:"server"`
	Site                basetypes.ObjectValue `tfsdk:"site"`
	User                basetypes.ObjectValue `tfsdk:"user"`
	state               attr.ValueState
}

func (v ScpUserFailoveripsV6Value) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 7)

	var val tftypes.Value
	var err error

	attrTypes["editable"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["network_prefix"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["network_prefix_length"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["server"] = basetypes.ObjectType{
		AttrTypes: ServerValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["site"] = basetypes.ObjectType{
		AttrTypes: SiteValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["user"] = basetypes.ObjectType{
		AttrTypes: UserValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 7)

		val, err = v.Editable.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["editable"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.NetworkPrefix.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["network_prefix"] = val

		val, err = v.NetworkPrefixLength.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["network_prefix_length"] = val

		val, err = v.Server.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["server"] = val

		val, err = v.Site.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["site"] = val

		val, err = v.User.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["user"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ScpUserFailoveripsV6Value) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ScpUserFailoveripsV6Value) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ScpUserFailoveripsV6Value) String() string {
	return "ScpUserFailoveripsV6Value"
}

func (v ScpUserFailoveripsV6Value) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var server basetypes.ObjectValue

	if v.Server.IsNull() {
		server = types.ObjectNull(
			ServerValue{}.AttributeTypes(ctx),
		)
	}

	if v.Server.IsUnknown() {
		server = types.ObjectUnknown(
			ServerValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Server.IsNull() && !v.Server.IsUnknown() {
		server = types.ObjectValueMust(
			ServerValue{}.AttributeTypes(ctx),
			v.Server.Attributes(),
		)
	}

	var site basetypes.ObjectValue

	if v.Site.IsNull() {
		site = types.ObjectNull(
			SiteValue{}.AttributeTypes(ctx),
		)
	}

	if v.Site.IsUnknown() {
		site = types.ObjectUnknown(
			SiteValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Site.IsNull() && !v.Site.IsUnknown() {
		site = types.ObjectValueMust(
			SiteValue{}.AttributeTypes(ctx),
			v.Site.Attributes(),
		)
	}

	var user basetypes.ObjectValue

	if v.User.IsNull() {
		user = types.ObjectNull(
			UserValue{}.AttributeTypes(ctx),
		)
	}

	if v.User.IsUnknown() {
		user = types.ObjectUnknown(
			UserValue{}.AttributeTypes(ctx),
		)
	}

	if !v.User.IsNull() && !v.User.IsUnknown() {
		user = types.ObjectValueMust(
			UserValue{}.AttributeTypes(ctx),
			v.User.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"editable":              basetypes.BoolType{},
		"id":                    basetypes.Int64Type{},
		"network_prefix":        basetypes.StringType{},
		"network_prefix_length": basetypes.Int64Type{},
		"server": basetypes.ObjectType{
			AttrTypes: ServerValue{}.AttributeTypes(ctx),
		},
		"site": basetypes.ObjectType{
			AttrTypes: SiteValue{}.AttributeTypes(ctx),
		},
		"user": basetypes.ObjectType{
			AttrTypes: UserValue{}.AttributeTypes(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"editable":              v.Editable,
			"id":                    v.Id,
			"network_prefix":        v.NetworkPrefix,
			"network_prefix_length": v.NetworkPrefixLength,
			"server":                server,
			"site":                  site,
			"user":                  user,
		})

	return objVal, diags
}

func (v ScpUserFailoveripsV6Value) Equal(o attr.Value) bool {
	other, ok := o.(ScpUserFailoveripsV6Value)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Editable.Equal(other.Editable) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.NetworkPrefix.Equal(other.NetworkPrefix) {
		return false
	}

	if !v.NetworkPrefixLength.Equal(other.NetworkPrefixLength) {
		return false
	}

	if !v.Server.Equal(other.Server) {
		return false
	}

	if !v.Site.Equal(other.Site) {
		return false
	}

	if !v.User.Equal(other.User) {
		return false
	}

	return true
}

func (v ScpUserFailoveripsV6Value) Type(ctx context.Context) attr.Type {
	return ScpUserFailoveripsV6Type{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ScpUserFailoveripsV6Value) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"editable":              basetypes.BoolType{},
		"id":                    basetypes.Int64Type{},
		"network_prefix":        basetypes.StringType{},
		"network_prefix_length": basetypes.Int64Type{},
		"server": basetypes.ObjectType{
			AttrTypes: ServerValue{}.AttributeTypes(ctx),
		},
		"site": basetypes.ObjectType{
			AttrTypes: SiteValue{}.AttributeTypes(ctx),
		},
		"user": basetypes.ObjectType{
			AttrTypes: UserValue{}.AttributeTypes(ctx),
		},
	}
}

var _ basetypes.ObjectTypable = ServerType{}

type ServerType struct {
	basetypes.ObjectType
}

func (t ServerType) Equal(o attr.Type) bool {
	other, ok := o.(ServerType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ServerType) String() string {
	return "ServerType"
}

func (t ServerType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ServerValue{
		Id:    idVal,
		Name:  nameVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewServerValueNull() ServerValue {
	return ServerValue{
		state: attr.ValueStateNull,
	}
}

func NewServerValueUnknown() ServerValue {
	return ServerValue{
		state: attr.ValueStateUnknown,
	}
}

func NewServerValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ServerValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ServerValue Attribute Value",
				"While creating a ServerValue value, a missing attribute value was detected. "+
					"A ServerValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ServerValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ServerValue Attribute Type",
				"While creating a ServerValue value, an invalid attribute value was detected. "+
					"A ServerValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ServerValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ServerValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ServerValue Attribute Value",
				"While creating a ServerValue value, an extra attribute value was detected. "+
					"A ServerValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ServerValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewServerValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewServerValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewServerValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return NewServerValueUnknown(), diags
	}

	return ServerValue{
		Id:    idVal,
		Name:  nameVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewServerValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ServerValue {
	object, diags := NewServerValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewServerValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ServerType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewServerValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewServerValueUnknown(), nil
	}

	if in.IsNull() {
		return NewServerValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewServerValueMust(ServerValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ServerType) ValueType(ctx context.Context) attr.Value {
	return ServerValue{}
}

var _ basetypes.ObjectValuable = ServerValue{}

type ServerValue struct {
	Id    basetypes.Int64Value  `tfsdk:"id"`
	Name  basetypes.StringValue `tfsdk:"name"`
	state attr.ValueState
}

func (v ServerValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ServerValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ServerValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ServerValue) String() string {
	return "ServerValue"
}

func (v ServerValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":   basetypes.Int64Type{},
		"name": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":   v.Id,
			"name": v.Name,
		})

	return objVal, diags
}

func (v ServerValue) Equal(o attr.Value) bool {
	other, ok := o.(ServerValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	return true
}

func (v ServerValue) Type(ctx context.Context) attr.Type {
	return ServerType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ServerValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.Int64Type{},
		"name": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = SiteType{}

type SiteType struct {
	basetypes.ObjectType
}

func (t SiteType) Equal(o attr.Type) bool {
	other, ok := o.(SiteType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t SiteType) String() string {
	return "SiteType"
}

func (t SiteType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	cityAttribute, ok := attributes["city"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`city is missing from object`)

		return nil, diags
	}

	cityVal, ok := cityAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`city expected to be basetypes.StringValue, was: %T`, cityAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return SiteValue{
		City:  cityVal,
		Id:    idVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewSiteValueNull() SiteValue {
	return SiteValue{
		state: attr.ValueStateNull,
	}
}

func NewSiteValueUnknown() SiteValue {
	return SiteValue{
		state: attr.ValueStateUnknown,
	}
}

func NewSiteValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (SiteValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing SiteValue Attribute Value",
				"While creating a SiteValue value, a missing attribute value was detected. "+
					"A SiteValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SiteValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid SiteValue Attribute Type",
				"While creating a SiteValue value, an invalid attribute value was detected. "+
					"A SiteValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SiteValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("SiteValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra SiteValue Attribute Value",
				"While creating a SiteValue value, an extra attribute value was detected. "+
					"A SiteValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra SiteValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewSiteValueUnknown(), diags
	}

	cityAttribute, ok := attributes["city"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`city is missing from object`)

		return NewSiteValueUnknown(), diags
	}

	cityVal, ok := cityAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`city expected to be basetypes.StringValue, was: %T`, cityAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewSiteValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	if diags.HasError() {
		return NewSiteValueUnknown(), diags
	}

	return SiteValue{
		City:  cityVal,
		Id:    idVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewSiteValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) SiteValue {
	object, diags := NewSiteValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewSiteValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t SiteType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewSiteValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewSiteValueUnknown(), nil
	}

	if in.IsNull() {
		return NewSiteValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewSiteValueMust(SiteValue{}.AttributeTypes(ctx), attributes), nil
}

func (t SiteType) ValueType(ctx context.Context) attr.Value {
	return SiteValue{}
}

var _ basetypes.ObjectValuable = SiteValue{}

type SiteValue struct {
	City  basetypes.StringValue `tfsdk:"city"`
	Id    basetypes.Int64Value  `tfsdk:"id"`
	state attr.ValueState
}

func (v SiteValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["city"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.City.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["city"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v SiteValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v SiteValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v SiteValue) String() string {
	return "SiteValue"
}

func (v SiteValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"city": basetypes.StringType{},
		"id":   basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"city": v.City,
			"id":   v.Id,
		})

	return objVal, diags
}

func (v SiteValue) Equal(o attr.Value) bool {
	other, ok := o.(SiteValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.City.Equal(other.City) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	return true
}

func (v SiteValue) Type(ctx context.Context) attr.Type {
	return SiteType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v SiteValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"city": basetypes.StringType{},
		"id":   basetypes.Int64Type{},
	}
}

var _ basetypes.ObjectTypable = UserType{}

type UserType struct {
	basetypes.ObjectType
}

func (t UserType) Equal(o attr.Type) bool {
	other, ok := o.(UserType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t UserType) String() string {
	return "UserType"
}

func (t UserType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	companyAttribute, ok := attributes["company"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`company is missing from object`)

		return nil, diags
	}

	companyVal, ok := companyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`company expected to be basetypes.StringValue, was: %T`, companyAttribute))
	}

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return nil, diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	firstnameAttribute, ok := attributes["firstname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`firstname is missing from object`)

		return nil, diags
	}

	firstnameVal, ok := firstnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`firstname expected to be basetypes.StringValue, was: %T`, firstnameAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	lastnameAttribute, ok := attributes["lastname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`lastname is missing from object`)

		return nil, diags
	}

	lastnameVal, ok := lastnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`lastname expected to be basetypes.StringValue, was: %T`, lastnameAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return nil, diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return UserValue{
		Company:   companyVal,
		Email:     emailVal,
		Firstname: firstnameVal,
		Id:        idVal,
		Lastname:  lastnameVal,
		Username:  usernameVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewUserValueNull() UserValue {
	return UserValue{
		state: attr.ValueStateNull,
	}
}

func NewUserValueUnknown() UserValue {
	return UserValue{
		state: attr.ValueStateUnknown,
	}
}

func NewUserValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (UserValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing UserValue Attribute Value",
				"While creating a UserValue value, a missing attribute value was detected. "+
					"A UserValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UserValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid UserValue Attribute Type",
				"While creating a UserValue value, an invalid attribute value was detected. "+
					"A UserValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UserValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("UserValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra UserValue Attribute Value",
				"While creating a UserValue value, an extra attribute value was detected. "+
					"A UserValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra UserValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewUserValueUnknown(), diags
	}

	companyAttribute, ok := attributes["company"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`company is missing from object`)

		return NewUserValueUnknown(), diags
	}

	companyVal, ok := companyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`company expected to be basetypes.StringValue, was: %T`, companyAttribute))
	}

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return NewUserValueUnknown(), diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	firstnameAttribute, ok := attributes["firstname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`firstname is missing from object`)

		return NewUserValueUnknown(), diags
	}

	firstnameVal, ok := firstnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`firstname expected to be basetypes.StringValue, was: %T`, firstnameAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewUserValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	lastnameAttribute, ok := attributes["lastname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`lastname is missing from object`)

		return NewUserValueUnknown(), diags
	}

	lastnameVal, ok := lastnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`lastname expected to be basetypes.StringValue, was: %T`, lastnameAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return NewUserValueUnknown(), diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	if diags.HasError() {
		return NewUserValueUnknown(), diags
	}

	return UserValue{
		Company:   companyVal,
		Email:     emailVal,
		Firstname: firstnameVal,
		Id:        idVal,
		Lastname:  lastnameVal,
		Username:  usernameVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewUserValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) UserValue {
	object, diags := NewUserValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewUserValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t UserType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewUserValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewUserValueUnknown(), nil
	}

	if in.IsNull() {
		return NewUserValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewUserValueMust(UserValue{}.AttributeTypes(ctx), attributes), nil
}

func (t UserType) ValueType(ctx context.Context) attr.Value {
	return UserValue{}
}

var _ basetypes.ObjectValuable = UserValue{}

type UserValue struct {
	Company   basetypes.StringValue `tfsdk:"company"`
	Email     basetypes.StringValue `tfsdk:"email"`
	Firstname basetypes.StringValue `tfsdk:"firstname"`
	Id        basetypes.Int64Value  `tfsdk:"id"`
	Lastname  basetypes.StringValue `tfsdk:"lastname"`
	Username  basetypes.StringValue `tfsdk:"username"`
	state     attr.ValueState
}

func (v UserValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["company"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["email"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["firstname"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["lastname"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["username"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.Company.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["company"] = val

		val, err = v.Email.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["email"] = val

		val, err = v.Firstname.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["firstname"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Lastname.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["lastname"] = val

		val, err = v.Username.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["username"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v UserValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v UserValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v UserValue) String() string {
	return "UserValue"
}

func (v UserValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"company":   basetypes.StringType{},
		"email":     basetypes.StringType{},
		"firstname": basetypes.StringType{},
		"id":        basetypes.Int64Type{},
		"lastname":  basetypes.StringType{},
		"username":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"company":   v.Company,
			"email":     v.Email,
			"firstname": v.Firstname,
			"id":        v.Id,
			"lastname":  v.Lastname,
			"username":  v.Username,
		})

	return objVal, diags
}

func (v UserValue) Equal(o attr.Value) bool {
	other, ok := o.(UserValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Company.Equal(other.Company) {
		return false
	}

	if !v.Email.Equal(other.Email) {
		return false
	}

	if !v.Firstname.Equal(other.Firstname) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Lastname.Equal(other.Lastname) {
		return false
	}

	if !v.Username.Equal(other.Username) {
		return false
	}

	return true
}

func (v UserValue) Type(ctx context.Context) attr.Type {
	return UserType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v UserValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"company":   basetypes.StringType{},
		"email":     basetypes.StringType{},
		"firstname": basetypes.StringType{},
		"id":        basetypes.Int64Type{},
		"lastname":  basetypes.StringType{},
		"username":  basetypes.StringType{},
	}
}
