// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scpservergpudriver

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpServerGpuDriverDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		MarkdownDescription: "Generate presigned download URL for GPU driver if available",
		Attributes: map[string]schema.Attribute{
			"filename": schema.StringAttribute{
				Computed: true,
			},
			"headers": schema.MapAttribute{
				ElementType: types.ListType{
					ElemType: types.StringType,
				},
				Computed: true,
			},
			"presigned_url": schema.StringAttribute{
				Computed: true,
			},
			"presigned_url_validity_duration_in_hours": schema.Int64Attribute{
				Computed: true,
			},
			"server_id": schema.Int64Attribute{
				Required:            true,
				Description:         "Server id",
				MarkdownDescription: "Server id",
			},
		},
	}
}

type ScpServerGpuDriverModel struct {
	Filename                            types.String `tfsdk:"filename"`
	Headers                             types.Map    `tfsdk:"headers"`
	PresignedUrl                        types.String `tfsdk:"presigned_url"`
	PresignedUrlValidityDurationInHours types.Int64  `tfsdk:"presigned_url_validity_duration_in_hours"`
	ServerId                            types.Int64  `tfsdk:"server_id"`
}
