// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scpuserimage

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpUserImageDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"filename": schema.StringAttribute{
				Computed: true,
			},
			"headers": schema.MapAttribute{
				ElementType: types.ListType{
					ElemType: types.StringType,
				},
				Computed: true,
			},
			"key": schema.StringAttribute{
				Required: true,
			},
			"presigned_url": schema.StringAttribute{
				Computed: true,
			},
			"presigned_url_validity_duration_in_hours": schema.Int64Attribute{
				Computed: true,
			},
			"user_id": schema.Int64Attribute{
				Required: true,
			},
		},
	}
}

type ScpUserImageModel struct {
	Filename                            types.String `tfsdk:"filename"`
	Headers                             types.Map    `tfsdk:"headers"`
	Key                                 types.String `tfsdk:"key"`
	PresignedUrl                        types.String `tfsdk:"presigned_url"`
	PresignedUrlValidityDurationInHours types.Int64  `tfsdk:"presigned_url_validity_duration_in_hours"`
	UserId                              types.Int64  `tfsdk:"user_id"`
}
