// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scpserverdisk

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpServerDiskDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		MarkdownDescription: "Get a disk of a server",
		Attributes: map[string]schema.Attribute{
			"allocation_in_mi_b": schema.Int64Attribute{
				Computed: true,
			},
			"capacity_in_mi_b": schema.Int64Attribute{
				Computed: true,
			},
			"disk_name": schema.StringAttribute{
				Required: true,
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"server_id": schema.Int64Attribute{
				Required: true,
			},
			"storage_driver": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type ScpServerDiskModel struct {
	AllocationInMiB types.Int64  `tfsdk:"allocation_in_mi_b"`
	CapacityInMiB   types.Int64  `tfsdk:"capacity_in_mi_b"`
	DiskName        types.String `tfsdk:"disk_name"`
	Name            types.String `tfsdk:"name"`
	ServerId        types.Int64  `tfsdk:"server_id"`
	StorageDriver   types.String `tfsdk:"storage_driver"`
}
