// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scpserversnapshot

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpServerSnapshotDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		MarkdownDescription: "Get a snapshot of a server.",
		Attributes: map[string]schema.Attribute{
			"creation_time": schema.StringAttribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Computed: true,
			},
			"disks": schema.ListAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"download_infos": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"filename": schema.StringAttribute{
						Computed: true,
					},
					"headers": schema.MapAttribute{
						ElementType: types.ListType{
							ElemType: types.StringType,
						},
						Computed: true,
					},
					"presigned_url": schema.StringAttribute{
						Computed: true,
					},
					"presigned_url_validity_duration_in_hours": schema.Int64Attribute{
						Computed: true,
					},
				},
				CustomType: DownloadInfosType{
					ObjectType: types.ObjectType{
						AttrTypes: DownloadInfosValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"exported": schema.BoolAttribute{
				Computed: true,
			},
			"exported_size_in_ki_b": schema.Int64Attribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"online": schema.BoolAttribute{
				Computed: true,
			},
			"server_id": schema.Int64Attribute{
				Required: true,
			},
			"state": schema.StringAttribute{
				Computed: true,
			},
			"uuid": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type ScpServerSnapshotModel struct {
	CreationTime      types.String       `tfsdk:"creation_time"`
	Description       types.String       `tfsdk:"description"`
	Disks             types.List         `tfsdk:"disks"`
	DownloadInfos     DownloadInfosValue `tfsdk:"download_infos"`
	Exported          types.Bool         `tfsdk:"exported"`
	ExportedSizeInKiB types.Int64        `tfsdk:"exported_size_in_ki_b"`
	Name              types.String       `tfsdk:"name"`
	Online            types.Bool         `tfsdk:"online"`
	ServerId          types.Int64        `tfsdk:"server_id"`
	State             types.String       `tfsdk:"state"`
	Uuid              types.String       `tfsdk:"uuid"`
}

var _ basetypes.ObjectTypable = DownloadInfosType{}

type DownloadInfosType struct {
	basetypes.ObjectType
}

func (t DownloadInfosType) Equal(o attr.Type) bool {
	other, ok := o.(DownloadInfosType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DownloadInfosType) String() string {
	return "DownloadInfosType"
}

func (t DownloadInfosType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	filenameAttribute, ok := attributes["filename"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`filename is missing from object`)

		return nil, diags
	}

	filenameVal, ok := filenameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`filename expected to be basetypes.StringValue, was: %T`, filenameAttribute))
	}

	headersAttribute, ok := attributes["headers"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`headers is missing from object`)

		return nil, diags
	}

	headersVal, ok := headersAttribute.(basetypes.MapValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`headers expected to be basetypes.MapValue, was: %T`, headersAttribute))
	}

	presignedUrlAttribute, ok := attributes["presigned_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`presigned_url is missing from object`)

		return nil, diags
	}

	presignedUrlVal, ok := presignedUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`presigned_url expected to be basetypes.StringValue, was: %T`, presignedUrlAttribute))
	}

	presignedUrlValidityDurationInHoursAttribute, ok := attributes["presigned_url_validity_duration_in_hours"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`presigned_url_validity_duration_in_hours is missing from object`)

		return nil, diags
	}

	presignedUrlValidityDurationInHoursVal, ok := presignedUrlValidityDurationInHoursAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`presigned_url_validity_duration_in_hours expected to be basetypes.Int64Value, was: %T`, presignedUrlValidityDurationInHoursAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DownloadInfosValue{
		Filename:                            filenameVal,
		Headers:                             headersVal,
		PresignedUrl:                        presignedUrlVal,
		PresignedUrlValidityDurationInHours: presignedUrlValidityDurationInHoursVal,
		state:                               attr.ValueStateKnown,
	}, diags
}

func NewDownloadInfosValueNull() DownloadInfosValue {
	return DownloadInfosValue{
		state: attr.ValueStateNull,
	}
}

func NewDownloadInfosValueUnknown() DownloadInfosValue {
	return DownloadInfosValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDownloadInfosValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DownloadInfosValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DownloadInfosValue Attribute Value",
				"While creating a DownloadInfosValue value, a missing attribute value was detected. "+
					"A DownloadInfosValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DownloadInfosValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DownloadInfosValue Attribute Type",
				"While creating a DownloadInfosValue value, an invalid attribute value was detected. "+
					"A DownloadInfosValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DownloadInfosValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DownloadInfosValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DownloadInfosValue Attribute Value",
				"While creating a DownloadInfosValue value, an extra attribute value was detected. "+
					"A DownloadInfosValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DownloadInfosValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDownloadInfosValueUnknown(), diags
	}

	filenameAttribute, ok := attributes["filename"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`filename is missing from object`)

		return NewDownloadInfosValueUnknown(), diags
	}

	filenameVal, ok := filenameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`filename expected to be basetypes.StringValue, was: %T`, filenameAttribute))
	}

	headersAttribute, ok := attributes["headers"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`headers is missing from object`)

		return NewDownloadInfosValueUnknown(), diags
	}

	headersVal, ok := headersAttribute.(basetypes.MapValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`headers expected to be basetypes.MapValue, was: %T`, headersAttribute))
	}

	presignedUrlAttribute, ok := attributes["presigned_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`presigned_url is missing from object`)

		return NewDownloadInfosValueUnknown(), diags
	}

	presignedUrlVal, ok := presignedUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`presigned_url expected to be basetypes.StringValue, was: %T`, presignedUrlAttribute))
	}

	presignedUrlValidityDurationInHoursAttribute, ok := attributes["presigned_url_validity_duration_in_hours"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`presigned_url_validity_duration_in_hours is missing from object`)

		return NewDownloadInfosValueUnknown(), diags
	}

	presignedUrlValidityDurationInHoursVal, ok := presignedUrlValidityDurationInHoursAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`presigned_url_validity_duration_in_hours expected to be basetypes.Int64Value, was: %T`, presignedUrlValidityDurationInHoursAttribute))
	}

	if diags.HasError() {
		return NewDownloadInfosValueUnknown(), diags
	}

	return DownloadInfosValue{
		Filename:                            filenameVal,
		Headers:                             headersVal,
		PresignedUrl:                        presignedUrlVal,
		PresignedUrlValidityDurationInHours: presignedUrlValidityDurationInHoursVal,
		state:                               attr.ValueStateKnown,
	}, diags
}

func NewDownloadInfosValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DownloadInfosValue {
	object, diags := NewDownloadInfosValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDownloadInfosValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DownloadInfosType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDownloadInfosValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDownloadInfosValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDownloadInfosValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDownloadInfosValueMust(DownloadInfosValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DownloadInfosType) ValueType(ctx context.Context) attr.Value {
	return DownloadInfosValue{}
}

var _ basetypes.ObjectValuable = DownloadInfosValue{}

type DownloadInfosValue struct {
	Filename                            basetypes.StringValue `tfsdk:"filename"`
	Headers                             basetypes.MapValue    `tfsdk:"headers"`
	PresignedUrl                        basetypes.StringValue `tfsdk:"presigned_url"`
	PresignedUrlValidityDurationInHours basetypes.Int64Value  `tfsdk:"presigned_url_validity_duration_in_hours"`
	state                               attr.ValueState
}

func (v DownloadInfosValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["filename"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["headers"] = basetypes.MapType{
		ElemType: types.ListType{
			ElemType: types.StringType,
		},
	}.TerraformType(ctx)
	attrTypes["presigned_url"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["presigned_url_validity_duration_in_hours"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.Filename.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["filename"] = val

		val, err = v.Headers.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["headers"] = val

		val, err = v.PresignedUrl.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["presigned_url"] = val

		val, err = v.PresignedUrlValidityDurationInHours.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["presigned_url_validity_duration_in_hours"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DownloadInfosValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DownloadInfosValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DownloadInfosValue) String() string {
	return "DownloadInfosValue"
}

func (v DownloadInfosValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var headersVal basetypes.MapValue
	switch {
	case v.Headers.IsUnknown():
		headersVal = types.MapUnknown(types.ListType{
			ElemType: types.StringType,
		})
	case v.Headers.IsNull():
		headersVal = types.MapNull(types.ListType{
			ElemType: types.StringType,
		})
	default:
		var d diag.Diagnostics
		headersVal, d = types.MapValue(types.ListType{
			ElemType: types.StringType,
		}, v.Headers.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"filename": basetypes.StringType{},
			"headers": basetypes.MapType{
				ElemType: types.ListType{
					ElemType: types.StringType,
				},
			},
			"presigned_url": basetypes.StringType{},
			"presigned_url_validity_duration_in_hours": basetypes.Int64Type{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"filename": basetypes.StringType{},
		"headers": basetypes.MapType{
			ElemType: types.ListType{
				ElemType: types.StringType,
			},
		},
		"presigned_url": basetypes.StringType{},
		"presigned_url_validity_duration_in_hours": basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"filename":      v.Filename,
			"headers":       headersVal,
			"presigned_url": v.PresignedUrl,
			"presigned_url_validity_duration_in_hours": v.PresignedUrlValidityDurationInHours,
		})

	return objVal, diags
}

func (v DownloadInfosValue) Equal(o attr.Value) bool {
	other, ok := o.(DownloadInfosValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Filename.Equal(other.Filename) {
		return false
	}

	if !v.Headers.Equal(other.Headers) {
		return false
	}

	if !v.PresignedUrl.Equal(other.PresignedUrl) {
		return false
	}

	if !v.PresignedUrlValidityDurationInHours.Equal(other.PresignedUrlValidityDurationInHours) {
		return false
	}

	return true
}

func (v DownloadInfosValue) Type(ctx context.Context) attr.Type {
	return DownloadInfosType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DownloadInfosValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"filename": basetypes.StringType{},
		"headers": basetypes.MapType{
			ElemType: types.ListType{
				ElemType: types.StringType,
			},
		},
		"presigned_url": basetypes.StringType{},
		"presigned_url_validity_duration_in_hours": basetypes.Int64Type{},
	}
}
