// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scpserverinterface

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpServerInterfaceDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"driver": schema.StringAttribute{
				Computed: true,
			},
			"ipv4addresses": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"cidr": schema.StringAttribute{
							Computed: true,
						},
						"destination_ip": schema.StringAttribute{
							Computed: true,
						},
						"editable": schema.BoolAttribute{
							Computed: true,
						},
						"gateway": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.Int64Attribute{
							Computed: true,
						},
						"interface_mac": schema.StringAttribute{
							Computed: true,
						},
						"ip": schema.StringAttribute{
							Computed: true,
						},
						"rdns": schema.StringAttribute{
							Computed: true,
						},
						"type": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: Ipv4addressesType{
						ObjectType: types.ObjectType{
							AttrTypes: Ipv4addressesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"ipv6addresses": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"cidr": schema.StringAttribute{
							Computed: true,
						},
						"destination_ip": schema.StringAttribute{
							Computed: true,
						},
						"editable": schema.BoolAttribute{
							Computed: true,
						},
						"gateway": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.Int64Attribute{
							Computed: true,
						},
						"interface_mac": schema.StringAttribute{
							Computed: true,
						},
						"link_local": schema.BoolAttribute{
							Computed: true,
						},
						"network_prefix": schema.StringAttribute{
							Computed: true,
						},
						"rdns": schema.MapAttribute{
							ElementType: types.StringType,
							Computed:    true,
						},
						"type": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: Ipv6addressesType{
						ObjectType: types.ObjectType{
							AttrTypes: Ipv6addressesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"load_rdns": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"mac": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^[a-fA-F0-9]{2}(:[a-fA-F0-9]{2}){5}$"), ""),
				},
			},
			"server_id": schema.Int64Attribute{
				Required: true,
			},
			"speed_in_mbits": schema.Int64Attribute{
				Computed: true,
			},
		},
	}
}

type ScpServerInterfaceModel struct {
	Driver        types.String `tfsdk:"driver"`
	Ipv4addresses types.List   `tfsdk:"ipv4addresses"`
	Ipv6addresses types.List   `tfsdk:"ipv6addresses"`
	LoadRdns      types.Bool   `tfsdk:"load_rdns"`
	Mac           types.String `tfsdk:"mac"`
	ServerId      types.Int64  `tfsdk:"server_id"`
	SpeedInMbits  types.Int64  `tfsdk:"speed_in_mbits"`
}

var _ basetypes.ObjectTypable = Ipv4addressesType{}

type Ipv4addressesType struct {
	basetypes.ObjectType
}

func (t Ipv4addressesType) Equal(o attr.Type) bool {
	other, ok := o.(Ipv4addressesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t Ipv4addressesType) String() string {
	return "Ipv4addressesType"
}

func (t Ipv4addressesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	cidrAttribute, ok := attributes["cidr"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cidr is missing from object`)

		return nil, diags
	}

	cidrVal, ok := cidrAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cidr expected to be basetypes.StringValue, was: %T`, cidrAttribute))
	}

	destinationIpAttribute, ok := attributes["destination_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`destination_ip is missing from object`)

		return nil, diags
	}

	destinationIpVal, ok := destinationIpAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`destination_ip expected to be basetypes.StringValue, was: %T`, destinationIpAttribute))
	}

	editableAttribute, ok := attributes["editable"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`editable is missing from object`)

		return nil, diags
	}

	editableVal, ok := editableAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`editable expected to be basetypes.BoolValue, was: %T`, editableAttribute))
	}

	gatewayAttribute, ok := attributes["gateway"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`gateway is missing from object`)

		return nil, diags
	}

	gatewayVal, ok := gatewayAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`gateway expected to be basetypes.StringValue, was: %T`, gatewayAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	interfaceMacAttribute, ok := attributes["interface_mac"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`interface_mac is missing from object`)

		return nil, diags
	}

	interfaceMacVal, ok := interfaceMacAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`interface_mac expected to be basetypes.StringValue, was: %T`, interfaceMacAttribute))
	}

	ipAttribute, ok := attributes["ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip is missing from object`)

		return nil, diags
	}

	ipVal, ok := ipAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip expected to be basetypes.StringValue, was: %T`, ipAttribute))
	}

	rdnsAttribute, ok := attributes["rdns"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rdns is missing from object`)

		return nil, diags
	}

	rdnsVal, ok := rdnsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rdns expected to be basetypes.StringValue, was: %T`, rdnsAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return Ipv4addressesValue{
		Cidr:              cidrVal,
		DestinationIp:     destinationIpVal,
		Editable:          editableVal,
		Gateway:           gatewayVal,
		Id:                idVal,
		InterfaceMac:      interfaceMacVal,
		Ip:                ipVal,
		Rdns:              rdnsVal,
		Ipv4addressesType: typeVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewIpv4addressesValueNull() Ipv4addressesValue {
	return Ipv4addressesValue{
		state: attr.ValueStateNull,
	}
}

func NewIpv4addressesValueUnknown() Ipv4addressesValue {
	return Ipv4addressesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewIpv4addressesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (Ipv4addressesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing Ipv4addressesValue Attribute Value",
				"While creating a Ipv4addressesValue value, a missing attribute value was detected. "+
					"A Ipv4addressesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Ipv4addressesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid Ipv4addressesValue Attribute Type",
				"While creating a Ipv4addressesValue value, an invalid attribute value was detected. "+
					"A Ipv4addressesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Ipv4addressesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("Ipv4addressesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra Ipv4addressesValue Attribute Value",
				"While creating a Ipv4addressesValue value, an extra attribute value was detected. "+
					"A Ipv4addressesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra Ipv4addressesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewIpv4addressesValueUnknown(), diags
	}

	cidrAttribute, ok := attributes["cidr"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cidr is missing from object`)

		return NewIpv4addressesValueUnknown(), diags
	}

	cidrVal, ok := cidrAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cidr expected to be basetypes.StringValue, was: %T`, cidrAttribute))
	}

	destinationIpAttribute, ok := attributes["destination_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`destination_ip is missing from object`)

		return NewIpv4addressesValueUnknown(), diags
	}

	destinationIpVal, ok := destinationIpAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`destination_ip expected to be basetypes.StringValue, was: %T`, destinationIpAttribute))
	}

	editableAttribute, ok := attributes["editable"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`editable is missing from object`)

		return NewIpv4addressesValueUnknown(), diags
	}

	editableVal, ok := editableAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`editable expected to be basetypes.BoolValue, was: %T`, editableAttribute))
	}

	gatewayAttribute, ok := attributes["gateway"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`gateway is missing from object`)

		return NewIpv4addressesValueUnknown(), diags
	}

	gatewayVal, ok := gatewayAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`gateway expected to be basetypes.StringValue, was: %T`, gatewayAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewIpv4addressesValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	interfaceMacAttribute, ok := attributes["interface_mac"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`interface_mac is missing from object`)

		return NewIpv4addressesValueUnknown(), diags
	}

	interfaceMacVal, ok := interfaceMacAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`interface_mac expected to be basetypes.StringValue, was: %T`, interfaceMacAttribute))
	}

	ipAttribute, ok := attributes["ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip is missing from object`)

		return NewIpv4addressesValueUnknown(), diags
	}

	ipVal, ok := ipAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip expected to be basetypes.StringValue, was: %T`, ipAttribute))
	}

	rdnsAttribute, ok := attributes["rdns"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rdns is missing from object`)

		return NewIpv4addressesValueUnknown(), diags
	}

	rdnsVal, ok := rdnsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rdns expected to be basetypes.StringValue, was: %T`, rdnsAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewIpv4addressesValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewIpv4addressesValueUnknown(), diags
	}

	return Ipv4addressesValue{
		Cidr:              cidrVal,
		DestinationIp:     destinationIpVal,
		Editable:          editableVal,
		Gateway:           gatewayVal,
		Id:                idVal,
		InterfaceMac:      interfaceMacVal,
		Ip:                ipVal,
		Rdns:              rdnsVal,
		Ipv4addressesType: typeVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewIpv4addressesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) Ipv4addressesValue {
	object, diags := NewIpv4addressesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewIpv4addressesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t Ipv4addressesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewIpv4addressesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewIpv4addressesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewIpv4addressesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewIpv4addressesValueMust(Ipv4addressesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t Ipv4addressesType) ValueType(ctx context.Context) attr.Value {
	return Ipv4addressesValue{}
}

var _ basetypes.ObjectValuable = Ipv4addressesValue{}

type Ipv4addressesValue struct {
	Cidr              basetypes.StringValue `tfsdk:"cidr"`
	DestinationIp     basetypes.StringValue `tfsdk:"destination_ip"`
	Editable          basetypes.BoolValue   `tfsdk:"editable"`
	Gateway           basetypes.StringValue `tfsdk:"gateway"`
	Id                basetypes.Int64Value  `tfsdk:"id"`
	InterfaceMac      basetypes.StringValue `tfsdk:"interface_mac"`
	Ip                basetypes.StringValue `tfsdk:"ip"`
	Rdns              basetypes.StringValue `tfsdk:"rdns"`
	Ipv4addressesType basetypes.StringValue `tfsdk:"type"`
	state             attr.ValueState
}

func (v Ipv4addressesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 9)

	var val tftypes.Value
	var err error

	attrTypes["cidr"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["destination_ip"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["editable"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["gateway"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["interface_mac"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["ip"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["rdns"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 9)

		val, err = v.Cidr.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cidr"] = val

		val, err = v.DestinationIp.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["destination_ip"] = val

		val, err = v.Editable.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["editable"] = val

		val, err = v.Gateway.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["gateway"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.InterfaceMac.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["interface_mac"] = val

		val, err = v.Ip.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip"] = val

		val, err = v.Rdns.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["rdns"] = val

		val, err = v.Ipv4addressesType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v Ipv4addressesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v Ipv4addressesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v Ipv4addressesValue) String() string {
	return "Ipv4addressesValue"
}

func (v Ipv4addressesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"cidr":           basetypes.StringType{},
		"destination_ip": basetypes.StringType{},
		"editable":       basetypes.BoolType{},
		"gateway":        basetypes.StringType{},
		"id":             basetypes.Int64Type{},
		"interface_mac":  basetypes.StringType{},
		"ip":             basetypes.StringType{},
		"rdns":           basetypes.StringType{},
		"type":           basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"cidr":           v.Cidr,
			"destination_ip": v.DestinationIp,
			"editable":       v.Editable,
			"gateway":        v.Gateway,
			"id":             v.Id,
			"interface_mac":  v.InterfaceMac,
			"ip":             v.Ip,
			"rdns":           v.Rdns,
			"type":           v.Ipv4addressesType,
		})

	return objVal, diags
}

func (v Ipv4addressesValue) Equal(o attr.Value) bool {
	other, ok := o.(Ipv4addressesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Cidr.Equal(other.Cidr) {
		return false
	}

	if !v.DestinationIp.Equal(other.DestinationIp) {
		return false
	}

	if !v.Editable.Equal(other.Editable) {
		return false
	}

	if !v.Gateway.Equal(other.Gateway) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.InterfaceMac.Equal(other.InterfaceMac) {
		return false
	}

	if !v.Ip.Equal(other.Ip) {
		return false
	}

	if !v.Rdns.Equal(other.Rdns) {
		return false
	}

	if !v.Ipv4addressesType.Equal(other.Ipv4addressesType) {
		return false
	}

	return true
}

func (v Ipv4addressesValue) Type(ctx context.Context) attr.Type {
	return Ipv4addressesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v Ipv4addressesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"cidr":           basetypes.StringType{},
		"destination_ip": basetypes.StringType{},
		"editable":       basetypes.BoolType{},
		"gateway":        basetypes.StringType{},
		"id":             basetypes.Int64Type{},
		"interface_mac":  basetypes.StringType{},
		"ip":             basetypes.StringType{},
		"rdns":           basetypes.StringType{},
		"type":           basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = Ipv6addressesType{}

type Ipv6addressesType struct {
	basetypes.ObjectType
}

func (t Ipv6addressesType) Equal(o attr.Type) bool {
	other, ok := o.(Ipv6addressesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t Ipv6addressesType) String() string {
	return "Ipv6addressesType"
}

func (t Ipv6addressesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	cidrAttribute, ok := attributes["cidr"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cidr is missing from object`)

		return nil, diags
	}

	cidrVal, ok := cidrAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cidr expected to be basetypes.StringValue, was: %T`, cidrAttribute))
	}

	destinationIpAttribute, ok := attributes["destination_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`destination_ip is missing from object`)

		return nil, diags
	}

	destinationIpVal, ok := destinationIpAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`destination_ip expected to be basetypes.StringValue, was: %T`, destinationIpAttribute))
	}

	editableAttribute, ok := attributes["editable"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`editable is missing from object`)

		return nil, diags
	}

	editableVal, ok := editableAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`editable expected to be basetypes.BoolValue, was: %T`, editableAttribute))
	}

	gatewayAttribute, ok := attributes["gateway"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`gateway is missing from object`)

		return nil, diags
	}

	gatewayVal, ok := gatewayAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`gateway expected to be basetypes.StringValue, was: %T`, gatewayAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	interfaceMacAttribute, ok := attributes["interface_mac"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`interface_mac is missing from object`)

		return nil, diags
	}

	interfaceMacVal, ok := interfaceMacAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`interface_mac expected to be basetypes.StringValue, was: %T`, interfaceMacAttribute))
	}

	linkLocalAttribute, ok := attributes["link_local"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`link_local is missing from object`)

		return nil, diags
	}

	linkLocalVal, ok := linkLocalAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`link_local expected to be basetypes.BoolValue, was: %T`, linkLocalAttribute))
	}

	networkPrefixAttribute, ok := attributes["network_prefix"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`network_prefix is missing from object`)

		return nil, diags
	}

	networkPrefixVal, ok := networkPrefixAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`network_prefix expected to be basetypes.StringValue, was: %T`, networkPrefixAttribute))
	}

	rdnsAttribute, ok := attributes["rdns"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rdns is missing from object`)

		return nil, diags
	}

	rdnsVal, ok := rdnsAttribute.(basetypes.MapValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rdns expected to be basetypes.MapValue, was: %T`, rdnsAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return Ipv6addressesValue{
		Cidr:              cidrVal,
		DestinationIp:     destinationIpVal,
		Editable:          editableVal,
		Gateway:           gatewayVal,
		Id:                idVal,
		InterfaceMac:      interfaceMacVal,
		LinkLocal:         linkLocalVal,
		NetworkPrefix:     networkPrefixVal,
		Rdns:              rdnsVal,
		Ipv6addressesType: typeVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewIpv6addressesValueNull() Ipv6addressesValue {
	return Ipv6addressesValue{
		state: attr.ValueStateNull,
	}
}

func NewIpv6addressesValueUnknown() Ipv6addressesValue {
	return Ipv6addressesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewIpv6addressesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (Ipv6addressesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing Ipv6addressesValue Attribute Value",
				"While creating a Ipv6addressesValue value, a missing attribute value was detected. "+
					"A Ipv6addressesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Ipv6addressesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid Ipv6addressesValue Attribute Type",
				"While creating a Ipv6addressesValue value, an invalid attribute value was detected. "+
					"A Ipv6addressesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Ipv6addressesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("Ipv6addressesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra Ipv6addressesValue Attribute Value",
				"While creating a Ipv6addressesValue value, an extra attribute value was detected. "+
					"A Ipv6addressesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra Ipv6addressesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewIpv6addressesValueUnknown(), diags
	}

	cidrAttribute, ok := attributes["cidr"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cidr is missing from object`)

		return NewIpv6addressesValueUnknown(), diags
	}

	cidrVal, ok := cidrAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cidr expected to be basetypes.StringValue, was: %T`, cidrAttribute))
	}

	destinationIpAttribute, ok := attributes["destination_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`destination_ip is missing from object`)

		return NewIpv6addressesValueUnknown(), diags
	}

	destinationIpVal, ok := destinationIpAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`destination_ip expected to be basetypes.StringValue, was: %T`, destinationIpAttribute))
	}

	editableAttribute, ok := attributes["editable"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`editable is missing from object`)

		return NewIpv6addressesValueUnknown(), diags
	}

	editableVal, ok := editableAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`editable expected to be basetypes.BoolValue, was: %T`, editableAttribute))
	}

	gatewayAttribute, ok := attributes["gateway"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`gateway is missing from object`)

		return NewIpv6addressesValueUnknown(), diags
	}

	gatewayVal, ok := gatewayAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`gateway expected to be basetypes.StringValue, was: %T`, gatewayAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewIpv6addressesValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	interfaceMacAttribute, ok := attributes["interface_mac"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`interface_mac is missing from object`)

		return NewIpv6addressesValueUnknown(), diags
	}

	interfaceMacVal, ok := interfaceMacAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`interface_mac expected to be basetypes.StringValue, was: %T`, interfaceMacAttribute))
	}

	linkLocalAttribute, ok := attributes["link_local"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`link_local is missing from object`)

		return NewIpv6addressesValueUnknown(), diags
	}

	linkLocalVal, ok := linkLocalAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`link_local expected to be basetypes.BoolValue, was: %T`, linkLocalAttribute))
	}

	networkPrefixAttribute, ok := attributes["network_prefix"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`network_prefix is missing from object`)

		return NewIpv6addressesValueUnknown(), diags
	}

	networkPrefixVal, ok := networkPrefixAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`network_prefix expected to be basetypes.StringValue, was: %T`, networkPrefixAttribute))
	}

	rdnsAttribute, ok := attributes["rdns"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rdns is missing from object`)

		return NewIpv6addressesValueUnknown(), diags
	}

	rdnsVal, ok := rdnsAttribute.(basetypes.MapValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rdns expected to be basetypes.MapValue, was: %T`, rdnsAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewIpv6addressesValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewIpv6addressesValueUnknown(), diags
	}

	return Ipv6addressesValue{
		Cidr:              cidrVal,
		DestinationIp:     destinationIpVal,
		Editable:          editableVal,
		Gateway:           gatewayVal,
		Id:                idVal,
		InterfaceMac:      interfaceMacVal,
		LinkLocal:         linkLocalVal,
		NetworkPrefix:     networkPrefixVal,
		Rdns:              rdnsVal,
		Ipv6addressesType: typeVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewIpv6addressesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) Ipv6addressesValue {
	object, diags := NewIpv6addressesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewIpv6addressesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t Ipv6addressesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewIpv6addressesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewIpv6addressesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewIpv6addressesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewIpv6addressesValueMust(Ipv6addressesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t Ipv6addressesType) ValueType(ctx context.Context) attr.Value {
	return Ipv6addressesValue{}
}

var _ basetypes.ObjectValuable = Ipv6addressesValue{}

type Ipv6addressesValue struct {
	Cidr              basetypes.StringValue `tfsdk:"cidr"`
	DestinationIp     basetypes.StringValue `tfsdk:"destination_ip"`
	Editable          basetypes.BoolValue   `tfsdk:"editable"`
	Gateway           basetypes.StringValue `tfsdk:"gateway"`
	Id                basetypes.Int64Value  `tfsdk:"id"`
	InterfaceMac      basetypes.StringValue `tfsdk:"interface_mac"`
	LinkLocal         basetypes.BoolValue   `tfsdk:"link_local"`
	NetworkPrefix     basetypes.StringValue `tfsdk:"network_prefix"`
	Rdns              basetypes.MapValue    `tfsdk:"rdns"`
	Ipv6addressesType basetypes.StringValue `tfsdk:"type"`
	state             attr.ValueState
}

func (v Ipv6addressesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 10)

	var val tftypes.Value
	var err error

	attrTypes["cidr"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["destination_ip"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["editable"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["gateway"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["interface_mac"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["link_local"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["network_prefix"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["rdns"] = basetypes.MapType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 10)

		val, err = v.Cidr.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cidr"] = val

		val, err = v.DestinationIp.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["destination_ip"] = val

		val, err = v.Editable.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["editable"] = val

		val, err = v.Gateway.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["gateway"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.InterfaceMac.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["interface_mac"] = val

		val, err = v.LinkLocal.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["link_local"] = val

		val, err = v.NetworkPrefix.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["network_prefix"] = val

		val, err = v.Rdns.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["rdns"] = val

		val, err = v.Ipv6addressesType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v Ipv6addressesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v Ipv6addressesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v Ipv6addressesValue) String() string {
	return "Ipv6addressesValue"
}

func (v Ipv6addressesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var rdnsVal basetypes.MapValue
	switch {
	case v.Rdns.IsUnknown():
		rdnsVal = types.MapUnknown(types.StringType)
	case v.Rdns.IsNull():
		rdnsVal = types.MapNull(types.StringType)
	default:
		var d diag.Diagnostics
		rdnsVal, d = types.MapValue(types.StringType, v.Rdns.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"cidr":           basetypes.StringType{},
			"destination_ip": basetypes.StringType{},
			"editable":       basetypes.BoolType{},
			"gateway":        basetypes.StringType{},
			"id":             basetypes.Int64Type{},
			"interface_mac":  basetypes.StringType{},
			"link_local":     basetypes.BoolType{},
			"network_prefix": basetypes.StringType{},
			"rdns": basetypes.MapType{
				ElemType: types.StringType,
			},
			"type": basetypes.StringType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"cidr":           basetypes.StringType{},
		"destination_ip": basetypes.StringType{},
		"editable":       basetypes.BoolType{},
		"gateway":        basetypes.StringType{},
		"id":             basetypes.Int64Type{},
		"interface_mac":  basetypes.StringType{},
		"link_local":     basetypes.BoolType{},
		"network_prefix": basetypes.StringType{},
		"rdns": basetypes.MapType{
			ElemType: types.StringType,
		},
		"type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"cidr":           v.Cidr,
			"destination_ip": v.DestinationIp,
			"editable":       v.Editable,
			"gateway":        v.Gateway,
			"id":             v.Id,
			"interface_mac":  v.InterfaceMac,
			"link_local":     v.LinkLocal,
			"network_prefix": v.NetworkPrefix,
			"rdns":           rdnsVal,
			"type":           v.Ipv6addressesType,
		})

	return objVal, diags
}

func (v Ipv6addressesValue) Equal(o attr.Value) bool {
	other, ok := o.(Ipv6addressesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Cidr.Equal(other.Cidr) {
		return false
	}

	if !v.DestinationIp.Equal(other.DestinationIp) {
		return false
	}

	if !v.Editable.Equal(other.Editable) {
		return false
	}

	if !v.Gateway.Equal(other.Gateway) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.InterfaceMac.Equal(other.InterfaceMac) {
		return false
	}

	if !v.LinkLocal.Equal(other.LinkLocal) {
		return false
	}

	if !v.NetworkPrefix.Equal(other.NetworkPrefix) {
		return false
	}

	if !v.Rdns.Equal(other.Rdns) {
		return false
	}

	if !v.Ipv6addressesType.Equal(other.Ipv6addressesType) {
		return false
	}

	return true
}

func (v Ipv6addressesValue) Type(ctx context.Context) attr.Type {
	return Ipv6addressesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v Ipv6addressesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"cidr":           basetypes.StringType{},
		"destination_ip": basetypes.StringType{},
		"editable":       basetypes.BoolType{},
		"gateway":        basetypes.StringType{},
		"id":             basetypes.Int64Type{},
		"interface_mac":  basetypes.StringType{},
		"link_local":     basetypes.BoolType{},
		"network_prefix": basetypes.StringType{},
		"rdns": basetypes.MapType{
			ElemType: types.StringType,
		},
		"type": basetypes.StringType{},
	}
}
