// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scpuserfirewallpolicy

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpUserFirewallPolicyDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.Int64Attribute{
				Required: true,
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"rules": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"action": schema.StringAttribute{
							Computed: true,
						},
						"description": schema.StringAttribute{
							Computed: true,
						},
						"destination_ports": schema.StringAttribute{
							Computed:            true,
							Description:         "Valid configurations are any port (null), single port (f.e. 1234) or port range (f.e. 1024-65535).",
							MarkdownDescription: "Valid configurations are any port (null), single port (f.e. 1234) or port range (f.e. 1024-65535).",
						},
						"destinations": schema.ListAttribute{
							ElementType:         types.StringType,
							Computed:            true,
							Description:         "Valid configurations are any IP (null or empty array), IPv4/IPv6 address (f.e. 192.0.2.1 or 2001:db8::) or IPv4 network / IPv6 prefix (f.e. 192.0.2.0/24 or 2001:db8::/32). If more than one IP/network is specified for the destination, the source must be empty (any) or contain only a single IP/network. If IPv4 addresses and IPv6 addresses are mixed in destinations, sources must be empty (any).",
							MarkdownDescription: "Valid configurations are any IP (null or empty array), IPv4/IPv6 address (f.e. 192.0.2.1 or 2001:db8::) or IPv4 network / IPv6 prefix (f.e. 192.0.2.0/24 or 2001:db8::/32). If more than one IP/network is specified for the destination, the source must be empty (any) or contain only a single IP/network. If IPv4 addresses and IPv6 addresses are mixed in destinations, sources must be empty (any).",
						},
						"direction": schema.StringAttribute{
							Computed: true,
						},
						"number_of_effective_rules": schema.Int64Attribute{
							Computed: true,
						},
						"protocol": schema.StringAttribute{
							Computed: true,
						},
						"source_ports": schema.StringAttribute{
							Computed:            true,
							Description:         "Valid configurations are any port (null), single port (f.e. 1234) or port range (f.e. 1024-65535).",
							MarkdownDescription: "Valid configurations are any port (null), single port (f.e. 1234) or port range (f.e. 1024-65535).",
						},
						"sources": schema.ListAttribute{
							ElementType:         types.StringType,
							Computed:            true,
							Description:         "Valid configurations are any IP (null or empty array), IPv4/IPv6 address (f.e. 192.0.2.1 or 2001:db8::) or IPv4 network / IPv6 prefix (f.e. 192.0.2.0/24 or 2001:db8::/32). If more than one IP/network is specified for the source, the destination must be empty (any) or contain only a single IP/network. If IPv4 addresses and IPv6 addresses are mixed in sources, destinations must empty (any).",
							MarkdownDescription: "Valid configurations are any IP (null or empty array), IPv4/IPv6 address (f.e. 192.0.2.1 or 2001:db8::) or IPv4 network / IPv6 prefix (f.e. 192.0.2.0/24 or 2001:db8::/32). If more than one IP/network is specified for the source, the destination must be empty (any) or contain only a single IP/network. If IPv4 addresses and IPv6 addresses are mixed in sources, destinations must empty (any).",
						},
					},
					CustomType: RulesType{
						ObjectType: types.ObjectType{
							AttrTypes: RulesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"user_id": schema.Int64Attribute{
				Required: true,
			},
		},
	}
}

type ScpUserFirewallPolicyModel struct {
	Description types.String `tfsdk:"description"`
	Id          types.Int64  `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	Rules       types.List   `tfsdk:"rules"`
	UserId      types.Int64  `tfsdk:"user_id"`
}

var _ basetypes.ObjectTypable = RulesType{}

type RulesType struct {
	basetypes.ObjectType
}

func (t RulesType) Equal(o attr.Type) bool {
	other, ok := o.(RulesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t RulesType) String() string {
	return "RulesType"
}

func (t RulesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	actionAttribute, ok := attributes["action"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`action is missing from object`)

		return nil, diags
	}

	actionVal, ok := actionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`action expected to be basetypes.StringValue, was: %T`, actionAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	destinationPortsAttribute, ok := attributes["destination_ports"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`destination_ports is missing from object`)

		return nil, diags
	}

	destinationPortsVal, ok := destinationPortsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`destination_ports expected to be basetypes.StringValue, was: %T`, destinationPortsAttribute))
	}

	destinationsAttribute, ok := attributes["destinations"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`destinations is missing from object`)

		return nil, diags
	}

	destinationsVal, ok := destinationsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`destinations expected to be basetypes.ListValue, was: %T`, destinationsAttribute))
	}

	directionAttribute, ok := attributes["direction"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`direction is missing from object`)

		return nil, diags
	}

	directionVal, ok := directionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`direction expected to be basetypes.StringValue, was: %T`, directionAttribute))
	}

	numberOfEffectiveRulesAttribute, ok := attributes["number_of_effective_rules"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`number_of_effective_rules is missing from object`)

		return nil, diags
	}

	numberOfEffectiveRulesVal, ok := numberOfEffectiveRulesAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`number_of_effective_rules expected to be basetypes.Int64Value, was: %T`, numberOfEffectiveRulesAttribute))
	}

	protocolAttribute, ok := attributes["protocol"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`protocol is missing from object`)

		return nil, diags
	}

	protocolVal, ok := protocolAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`protocol expected to be basetypes.StringValue, was: %T`, protocolAttribute))
	}

	sourcePortsAttribute, ok := attributes["source_ports"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`source_ports is missing from object`)

		return nil, diags
	}

	sourcePortsVal, ok := sourcePortsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`source_ports expected to be basetypes.StringValue, was: %T`, sourcePortsAttribute))
	}

	sourcesAttribute, ok := attributes["sources"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`sources is missing from object`)

		return nil, diags
	}

	sourcesVal, ok := sourcesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`sources expected to be basetypes.ListValue, was: %T`, sourcesAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return RulesValue{
		Action:                 actionVal,
		Description:            descriptionVal,
		DestinationPorts:       destinationPortsVal,
		Destinations:           destinationsVal,
		Direction:              directionVal,
		NumberOfEffectiveRules: numberOfEffectiveRulesVal,
		Protocol:               protocolVal,
		SourcePorts:            sourcePortsVal,
		Sources:                sourcesVal,
		state:                  attr.ValueStateKnown,
	}, diags
}

func NewRulesValueNull() RulesValue {
	return RulesValue{
		state: attr.ValueStateNull,
	}
}

func NewRulesValueUnknown() RulesValue {
	return RulesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewRulesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (RulesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing RulesValue Attribute Value",
				"While creating a RulesValue value, a missing attribute value was detected. "+
					"A RulesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RulesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid RulesValue Attribute Type",
				"While creating a RulesValue value, an invalid attribute value was detected. "+
					"A RulesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RulesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("RulesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra RulesValue Attribute Value",
				"While creating a RulesValue value, an extra attribute value was detected. "+
					"A RulesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra RulesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewRulesValueUnknown(), diags
	}

	actionAttribute, ok := attributes["action"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`action is missing from object`)

		return NewRulesValueUnknown(), diags
	}

	actionVal, ok := actionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`action expected to be basetypes.StringValue, was: %T`, actionAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewRulesValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	destinationPortsAttribute, ok := attributes["destination_ports"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`destination_ports is missing from object`)

		return NewRulesValueUnknown(), diags
	}

	destinationPortsVal, ok := destinationPortsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`destination_ports expected to be basetypes.StringValue, was: %T`, destinationPortsAttribute))
	}

	destinationsAttribute, ok := attributes["destinations"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`destinations is missing from object`)

		return NewRulesValueUnknown(), diags
	}

	destinationsVal, ok := destinationsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`destinations expected to be basetypes.ListValue, was: %T`, destinationsAttribute))
	}

	directionAttribute, ok := attributes["direction"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`direction is missing from object`)

		return NewRulesValueUnknown(), diags
	}

	directionVal, ok := directionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`direction expected to be basetypes.StringValue, was: %T`, directionAttribute))
	}

	numberOfEffectiveRulesAttribute, ok := attributes["number_of_effective_rules"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`number_of_effective_rules is missing from object`)

		return NewRulesValueUnknown(), diags
	}

	numberOfEffectiveRulesVal, ok := numberOfEffectiveRulesAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`number_of_effective_rules expected to be basetypes.Int64Value, was: %T`, numberOfEffectiveRulesAttribute))
	}

	protocolAttribute, ok := attributes["protocol"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`protocol is missing from object`)

		return NewRulesValueUnknown(), diags
	}

	protocolVal, ok := protocolAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`protocol expected to be basetypes.StringValue, was: %T`, protocolAttribute))
	}

	sourcePortsAttribute, ok := attributes["source_ports"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`source_ports is missing from object`)

		return NewRulesValueUnknown(), diags
	}

	sourcePortsVal, ok := sourcePortsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`source_ports expected to be basetypes.StringValue, was: %T`, sourcePortsAttribute))
	}

	sourcesAttribute, ok := attributes["sources"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`sources is missing from object`)

		return NewRulesValueUnknown(), diags
	}

	sourcesVal, ok := sourcesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`sources expected to be basetypes.ListValue, was: %T`, sourcesAttribute))
	}

	if diags.HasError() {
		return NewRulesValueUnknown(), diags
	}

	return RulesValue{
		Action:                 actionVal,
		Description:            descriptionVal,
		DestinationPorts:       destinationPortsVal,
		Destinations:           destinationsVal,
		Direction:              directionVal,
		NumberOfEffectiveRules: numberOfEffectiveRulesVal,
		Protocol:               protocolVal,
		SourcePorts:            sourcePortsVal,
		Sources:                sourcesVal,
		state:                  attr.ValueStateKnown,
	}, diags
}

func NewRulesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) RulesValue {
	object, diags := NewRulesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewRulesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t RulesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewRulesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewRulesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewRulesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewRulesValueMust(RulesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t RulesType) ValueType(ctx context.Context) attr.Value {
	return RulesValue{}
}

var _ basetypes.ObjectValuable = RulesValue{}

type RulesValue struct {
	Action                 basetypes.StringValue `tfsdk:"action"`
	Description            basetypes.StringValue `tfsdk:"description"`
	DestinationPorts       basetypes.StringValue `tfsdk:"destination_ports"`
	Destinations           basetypes.ListValue   `tfsdk:"destinations"`
	Direction              basetypes.StringValue `tfsdk:"direction"`
	NumberOfEffectiveRules basetypes.Int64Value  `tfsdk:"number_of_effective_rules"`
	Protocol               basetypes.StringValue `tfsdk:"protocol"`
	SourcePorts            basetypes.StringValue `tfsdk:"source_ports"`
	Sources                basetypes.ListValue   `tfsdk:"sources"`
	state                  attr.ValueState
}

func (v RulesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 9)

	var val tftypes.Value
	var err error

	attrTypes["action"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["destination_ports"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["destinations"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["direction"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["number_of_effective_rules"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["protocol"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["source_ports"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["sources"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 9)

		val, err = v.Action.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["action"] = val

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.DestinationPorts.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["destination_ports"] = val

		val, err = v.Destinations.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["destinations"] = val

		val, err = v.Direction.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["direction"] = val

		val, err = v.NumberOfEffectiveRules.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["number_of_effective_rules"] = val

		val, err = v.Protocol.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["protocol"] = val

		val, err = v.SourcePorts.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["source_ports"] = val

		val, err = v.Sources.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["sources"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v RulesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v RulesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v RulesValue) String() string {
	return "RulesValue"
}

func (v RulesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var destinationsVal basetypes.ListValue
	switch {
	case v.Destinations.IsUnknown():
		destinationsVal = types.ListUnknown(types.StringType)
	case v.Destinations.IsNull():
		destinationsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		destinationsVal, d = types.ListValue(types.StringType, v.Destinations.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"action":            basetypes.StringType{},
			"description":       basetypes.StringType{},
			"destination_ports": basetypes.StringType{},
			"destinations": basetypes.ListType{
				ElemType: types.StringType,
			},
			"direction":                 basetypes.StringType{},
			"number_of_effective_rules": basetypes.Int64Type{},
			"protocol":                  basetypes.StringType{},
			"source_ports":              basetypes.StringType{},
			"sources": basetypes.ListType{
				ElemType: types.StringType,
			},
		}), diags
	}

	var sourcesVal basetypes.ListValue
	switch {
	case v.Sources.IsUnknown():
		sourcesVal = types.ListUnknown(types.StringType)
	case v.Sources.IsNull():
		sourcesVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		sourcesVal, d = types.ListValue(types.StringType, v.Sources.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"action":            basetypes.StringType{},
			"description":       basetypes.StringType{},
			"destination_ports": basetypes.StringType{},
			"destinations": basetypes.ListType{
				ElemType: types.StringType,
			},
			"direction":                 basetypes.StringType{},
			"number_of_effective_rules": basetypes.Int64Type{},
			"protocol":                  basetypes.StringType{},
			"source_ports":              basetypes.StringType{},
			"sources": basetypes.ListType{
				ElemType: types.StringType,
			},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"action":            basetypes.StringType{},
		"description":       basetypes.StringType{},
		"destination_ports": basetypes.StringType{},
		"destinations": basetypes.ListType{
			ElemType: types.StringType,
		},
		"direction":                 basetypes.StringType{},
		"number_of_effective_rules": basetypes.Int64Type{},
		"protocol":                  basetypes.StringType{},
		"source_ports":              basetypes.StringType{},
		"sources": basetypes.ListType{
			ElemType: types.StringType,
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"action":                    v.Action,
			"description":               v.Description,
			"destination_ports":         v.DestinationPorts,
			"destinations":              destinationsVal,
			"direction":                 v.Direction,
			"number_of_effective_rules": v.NumberOfEffectiveRules,
			"protocol":                  v.Protocol,
			"source_ports":              v.SourcePorts,
			"sources":                   sourcesVal,
		})

	return objVal, diags
}

func (v RulesValue) Equal(o attr.Value) bool {
	other, ok := o.(RulesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Action.Equal(other.Action) {
		return false
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.DestinationPorts.Equal(other.DestinationPorts) {
		return false
	}

	if !v.Destinations.Equal(other.Destinations) {
		return false
	}

	if !v.Direction.Equal(other.Direction) {
		return false
	}

	if !v.NumberOfEffectiveRules.Equal(other.NumberOfEffectiveRules) {
		return false
	}

	if !v.Protocol.Equal(other.Protocol) {
		return false
	}

	if !v.SourcePorts.Equal(other.SourcePorts) {
		return false
	}

	if !v.Sources.Equal(other.Sources) {
		return false
	}

	return true
}

func (v RulesValue) Type(ctx context.Context) attr.Type {
	return RulesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v RulesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"action":            basetypes.StringType{},
		"description":       basetypes.StringType{},
		"destination_ports": basetypes.StringType{},
		"destinations": basetypes.ListType{
			ElemType: types.StringType,
		},
		"direction":                 basetypes.StringType{},
		"number_of_effective_rules": basetypes.Int64Type{},
		"protocol":                  basetypes.StringType{},
		"source_ports":              basetypes.StringType{},
		"sources": basetypes.ListType{
			ElemType: types.StringType,
		},
	}
}
