// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scpuserlogs

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpUserLogsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		MarkdownDescription: "Get user logs",
		Attributes: map[string]schema.Attribute{
			"limit": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				Validators: []validator.Int64{
					int64validator.Between(0, 2147483647),
				},
			},
			"offset": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				Validators: []validator.Int64{
					int64validator.Between(0, 2147483647),
				},
			},
			"scp_user_logs": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"date": schema.StringAttribute{
							Computed: true,
						},
						"executing_user": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"company": schema.StringAttribute{
									Computed: true,
								},
								"email": schema.StringAttribute{
									Computed: true,
								},
								"firstname": schema.StringAttribute{
									Computed: true,
								},
								"id": schema.Int64Attribute{
									Computed: true,
								},
								"lastname": schema.StringAttribute{
									Computed: true,
								},
								"username": schema.StringAttribute{
									Computed: true,
								},
							},
							CustomType: ExecutingUserType{
								ObjectType: types.ObjectType{
									AttrTypes: ExecutingUserValue{}.AttributeTypes(ctx),
								},
							},
							Computed: true,
						},
						"log_key": schema.StringAttribute{
							Computed: true,
						},
						"message": schema.StringAttribute{
							Computed: true,
						},
						"type": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: ScpUserLogsType{
						ObjectType: types.ObjectType{
							AttrTypes: ScpUserLogsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"user_id": schema.Int64Attribute{
				Required:            true,
				Description:         "User id",
				MarkdownDescription: "User id",
			},
		},
	}
}

type ScpUserLogsModel struct {
	Limit       types.Int64 `tfsdk:"limit"`
	Offset      types.Int64 `tfsdk:"offset"`
	ScpUserLogs types.Set   `tfsdk:"scp_user_logs"`
	UserId      types.Int64 `tfsdk:"user_id"`
}

var _ basetypes.ObjectTypable = ScpUserLogsType{}

type ScpUserLogsType struct {
	basetypes.ObjectType
}

func (t ScpUserLogsType) Equal(o attr.Type) bool {
	other, ok := o.(ScpUserLogsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ScpUserLogsType) String() string {
	return "ScpUserLogsType"
}

func (t ScpUserLogsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	dateAttribute, ok := attributes["date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`date is missing from object`)

		return nil, diags
	}

	dateVal, ok := dateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`date expected to be basetypes.StringValue, was: %T`, dateAttribute))
	}

	executingUserAttribute, ok := attributes["executing_user"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`executing_user is missing from object`)

		return nil, diags
	}

	executingUserVal, ok := executingUserAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`executing_user expected to be basetypes.ObjectValue, was: %T`, executingUserAttribute))
	}

	logKeyAttribute, ok := attributes["log_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`log_key is missing from object`)

		return nil, diags
	}

	logKeyVal, ok := logKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`log_key expected to be basetypes.StringValue, was: %T`, logKeyAttribute))
	}

	messageAttribute, ok := attributes["message"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`message is missing from object`)

		return nil, diags
	}

	messageVal, ok := messageAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`message expected to be basetypes.StringValue, was: %T`, messageAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ScpUserLogsValue{
		Date:            dateVal,
		ExecutingUser:   executingUserVal,
		LogKey:          logKeyVal,
		Message:         messageVal,
		ScpUserLogsType: typeVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewScpUserLogsValueNull() ScpUserLogsValue {
	return ScpUserLogsValue{
		state: attr.ValueStateNull,
	}
}

func NewScpUserLogsValueUnknown() ScpUserLogsValue {
	return ScpUserLogsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewScpUserLogsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ScpUserLogsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ScpUserLogsValue Attribute Value",
				"While creating a ScpUserLogsValue value, a missing attribute value was detected. "+
					"A ScpUserLogsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScpUserLogsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ScpUserLogsValue Attribute Type",
				"While creating a ScpUserLogsValue value, an invalid attribute value was detected. "+
					"A ScpUserLogsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScpUserLogsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ScpUserLogsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ScpUserLogsValue Attribute Value",
				"While creating a ScpUserLogsValue value, an extra attribute value was detected. "+
					"A ScpUserLogsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ScpUserLogsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewScpUserLogsValueUnknown(), diags
	}

	dateAttribute, ok := attributes["date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`date is missing from object`)

		return NewScpUserLogsValueUnknown(), diags
	}

	dateVal, ok := dateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`date expected to be basetypes.StringValue, was: %T`, dateAttribute))
	}

	executingUserAttribute, ok := attributes["executing_user"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`executing_user is missing from object`)

		return NewScpUserLogsValueUnknown(), diags
	}

	executingUserVal, ok := executingUserAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`executing_user expected to be basetypes.ObjectValue, was: %T`, executingUserAttribute))
	}

	logKeyAttribute, ok := attributes["log_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`log_key is missing from object`)

		return NewScpUserLogsValueUnknown(), diags
	}

	logKeyVal, ok := logKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`log_key expected to be basetypes.StringValue, was: %T`, logKeyAttribute))
	}

	messageAttribute, ok := attributes["message"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`message is missing from object`)

		return NewScpUserLogsValueUnknown(), diags
	}

	messageVal, ok := messageAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`message expected to be basetypes.StringValue, was: %T`, messageAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewScpUserLogsValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewScpUserLogsValueUnknown(), diags
	}

	return ScpUserLogsValue{
		Date:            dateVal,
		ExecutingUser:   executingUserVal,
		LogKey:          logKeyVal,
		Message:         messageVal,
		ScpUserLogsType: typeVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewScpUserLogsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ScpUserLogsValue {
	object, diags := NewScpUserLogsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewScpUserLogsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ScpUserLogsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewScpUserLogsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewScpUserLogsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewScpUserLogsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewScpUserLogsValueMust(ScpUserLogsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ScpUserLogsType) ValueType(ctx context.Context) attr.Value {
	return ScpUserLogsValue{}
}

var _ basetypes.ObjectValuable = ScpUserLogsValue{}

type ScpUserLogsValue struct {
	Date            basetypes.StringValue `tfsdk:"date"`
	ExecutingUser   basetypes.ObjectValue `tfsdk:"executing_user"`
	LogKey          basetypes.StringValue `tfsdk:"log_key"`
	Message         basetypes.StringValue `tfsdk:"message"`
	ScpUserLogsType basetypes.StringValue `tfsdk:"type"`
	state           attr.ValueState
}

func (v ScpUserLogsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["date"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["executing_user"] = basetypes.ObjectType{
		AttrTypes: ExecutingUserValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["log_key"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["message"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.Date.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["date"] = val

		val, err = v.ExecutingUser.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["executing_user"] = val

		val, err = v.LogKey.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["log_key"] = val

		val, err = v.Message.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["message"] = val

		val, err = v.ScpUserLogsType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ScpUserLogsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ScpUserLogsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ScpUserLogsValue) String() string {
	return "ScpUserLogsValue"
}

func (v ScpUserLogsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var executingUser basetypes.ObjectValue

	if v.ExecutingUser.IsNull() {
		executingUser = types.ObjectNull(
			ExecutingUserValue{}.AttributeTypes(ctx),
		)
	}

	if v.ExecutingUser.IsUnknown() {
		executingUser = types.ObjectUnknown(
			ExecutingUserValue{}.AttributeTypes(ctx),
		)
	}

	if !v.ExecutingUser.IsNull() && !v.ExecutingUser.IsUnknown() {
		executingUser = types.ObjectValueMust(
			ExecutingUserValue{}.AttributeTypes(ctx),
			v.ExecutingUser.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"date": basetypes.StringType{},
		"executing_user": basetypes.ObjectType{
			AttrTypes: ExecutingUserValue{}.AttributeTypes(ctx),
		},
		"log_key": basetypes.StringType{},
		"message": basetypes.StringType{},
		"type":    basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"date":           v.Date,
			"executing_user": executingUser,
			"log_key":        v.LogKey,
			"message":        v.Message,
			"type":           v.ScpUserLogsType,
		})

	return objVal, diags
}

func (v ScpUserLogsValue) Equal(o attr.Value) bool {
	other, ok := o.(ScpUserLogsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Date.Equal(other.Date) {
		return false
	}

	if !v.ExecutingUser.Equal(other.ExecutingUser) {
		return false
	}

	if !v.LogKey.Equal(other.LogKey) {
		return false
	}

	if !v.Message.Equal(other.Message) {
		return false
	}

	if !v.ScpUserLogsType.Equal(other.ScpUserLogsType) {
		return false
	}

	return true
}

func (v ScpUserLogsValue) Type(ctx context.Context) attr.Type {
	return ScpUserLogsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ScpUserLogsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"date": basetypes.StringType{},
		"executing_user": basetypes.ObjectType{
			AttrTypes: ExecutingUserValue{}.AttributeTypes(ctx),
		},
		"log_key": basetypes.StringType{},
		"message": basetypes.StringType{},
		"type":    basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ExecutingUserType{}

type ExecutingUserType struct {
	basetypes.ObjectType
}

func (t ExecutingUserType) Equal(o attr.Type) bool {
	other, ok := o.(ExecutingUserType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ExecutingUserType) String() string {
	return "ExecutingUserType"
}

func (t ExecutingUserType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	companyAttribute, ok := attributes["company"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`company is missing from object`)

		return nil, diags
	}

	companyVal, ok := companyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`company expected to be basetypes.StringValue, was: %T`, companyAttribute))
	}

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return nil, diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	firstnameAttribute, ok := attributes["firstname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`firstname is missing from object`)

		return nil, diags
	}

	firstnameVal, ok := firstnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`firstname expected to be basetypes.StringValue, was: %T`, firstnameAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	lastnameAttribute, ok := attributes["lastname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`lastname is missing from object`)

		return nil, diags
	}

	lastnameVal, ok := lastnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`lastname expected to be basetypes.StringValue, was: %T`, lastnameAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return nil, diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ExecutingUserValue{
		Company:   companyVal,
		Email:     emailVal,
		Firstname: firstnameVal,
		Id:        idVal,
		Lastname:  lastnameVal,
		Username:  usernameVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewExecutingUserValueNull() ExecutingUserValue {
	return ExecutingUserValue{
		state: attr.ValueStateNull,
	}
}

func NewExecutingUserValueUnknown() ExecutingUserValue {
	return ExecutingUserValue{
		state: attr.ValueStateUnknown,
	}
}

func NewExecutingUserValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ExecutingUserValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ExecutingUserValue Attribute Value",
				"While creating a ExecutingUserValue value, a missing attribute value was detected. "+
					"A ExecutingUserValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ExecutingUserValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ExecutingUserValue Attribute Type",
				"While creating a ExecutingUserValue value, an invalid attribute value was detected. "+
					"A ExecutingUserValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ExecutingUserValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ExecutingUserValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ExecutingUserValue Attribute Value",
				"While creating a ExecutingUserValue value, an extra attribute value was detected. "+
					"A ExecutingUserValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ExecutingUserValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewExecutingUserValueUnknown(), diags
	}

	companyAttribute, ok := attributes["company"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`company is missing from object`)

		return NewExecutingUserValueUnknown(), diags
	}

	companyVal, ok := companyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`company expected to be basetypes.StringValue, was: %T`, companyAttribute))
	}

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return NewExecutingUserValueUnknown(), diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	firstnameAttribute, ok := attributes["firstname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`firstname is missing from object`)

		return NewExecutingUserValueUnknown(), diags
	}

	firstnameVal, ok := firstnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`firstname expected to be basetypes.StringValue, was: %T`, firstnameAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewExecutingUserValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	lastnameAttribute, ok := attributes["lastname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`lastname is missing from object`)

		return NewExecutingUserValueUnknown(), diags
	}

	lastnameVal, ok := lastnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`lastname expected to be basetypes.StringValue, was: %T`, lastnameAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return NewExecutingUserValueUnknown(), diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	if diags.HasError() {
		return NewExecutingUserValueUnknown(), diags
	}

	return ExecutingUserValue{
		Company:   companyVal,
		Email:     emailVal,
		Firstname: firstnameVal,
		Id:        idVal,
		Lastname:  lastnameVal,
		Username:  usernameVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewExecutingUserValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ExecutingUserValue {
	object, diags := NewExecutingUserValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewExecutingUserValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ExecutingUserType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewExecutingUserValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewExecutingUserValueUnknown(), nil
	}

	if in.IsNull() {
		return NewExecutingUserValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewExecutingUserValueMust(ExecutingUserValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ExecutingUserType) ValueType(ctx context.Context) attr.Value {
	return ExecutingUserValue{}
}

var _ basetypes.ObjectValuable = ExecutingUserValue{}

type ExecutingUserValue struct {
	Company   basetypes.StringValue `tfsdk:"company"`
	Email     basetypes.StringValue `tfsdk:"email"`
	Firstname basetypes.StringValue `tfsdk:"firstname"`
	Id        basetypes.Int64Value  `tfsdk:"id"`
	Lastname  basetypes.StringValue `tfsdk:"lastname"`
	Username  basetypes.StringValue `tfsdk:"username"`
	state     attr.ValueState
}

func (v ExecutingUserValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["company"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["email"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["firstname"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["lastname"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["username"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.Company.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["company"] = val

		val, err = v.Email.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["email"] = val

		val, err = v.Firstname.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["firstname"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Lastname.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["lastname"] = val

		val, err = v.Username.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["username"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ExecutingUserValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ExecutingUserValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ExecutingUserValue) String() string {
	return "ExecutingUserValue"
}

func (v ExecutingUserValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"company":   basetypes.StringType{},
		"email":     basetypes.StringType{},
		"firstname": basetypes.StringType{},
		"id":        basetypes.Int64Type{},
		"lastname":  basetypes.StringType{},
		"username":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"company":   v.Company,
			"email":     v.Email,
			"firstname": v.Firstname,
			"id":        v.Id,
			"lastname":  v.Lastname,
			"username":  v.Username,
		})

	return objVal, diags
}

func (v ExecutingUserValue) Equal(o attr.Value) bool {
	other, ok := o.(ExecutingUserValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Company.Equal(other.Company) {
		return false
	}

	if !v.Email.Equal(other.Email) {
		return false
	}

	if !v.Firstname.Equal(other.Firstname) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Lastname.Equal(other.Lastname) {
		return false
	}

	if !v.Username.Equal(other.Username) {
		return false
	}

	return true
}

func (v ExecutingUserValue) Type(ctx context.Context) attr.Type {
	return ExecutingUserType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ExecutingUserValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"company":   basetypes.StringType{},
		"email":     basetypes.StringType{},
		"firstname": basetypes.StringType{},
		"id":        basetypes.Int64Type{},
		"lastname":  basetypes.StringType{},
		"username":  basetypes.StringType{},
	}
}
