// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scpserveriso

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpServerIsoDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"iso": schema.StringAttribute{
				Computed: true,
			},
			"iso_attached": schema.BoolAttribute{
				Computed: true,
			},
			"server_id": schema.Int64Attribute{
				Required: true,
			},
		},
	}
}

type ScpServerIsoModel struct {
	Iso         types.String `tfsdk:"iso"`
	IsoAttached types.Bool   `tfsdk:"iso_attached"`
	ServerId    types.Int64  `tfsdk:"server_id"`
}
