// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scpserverisoimages

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpServerIsoimagesDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"scp_server_isoimages": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"architecture": schema.StringAttribute{
							Computed: true,
						},
						"description": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.Int64Attribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: ScpServerIsoimagesType{
						ObjectType: types.ObjectType{
							AttrTypes: ScpServerIsoimagesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"server_id": schema.Int64Attribute{
				Required: true,
			},
		},
	}
}

type ScpServerIsoimagesModel struct {
	ScpServerIsoimages types.Set   `tfsdk:"scp_server_isoimages"`
	ServerId           types.Int64 `tfsdk:"server_id"`
}

var _ basetypes.ObjectTypable = ScpServerIsoimagesType{}

type ScpServerIsoimagesType struct {
	basetypes.ObjectType
}

func (t ScpServerIsoimagesType) Equal(o attr.Type) bool {
	other, ok := o.(ScpServerIsoimagesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ScpServerIsoimagesType) String() string {
	return "ScpServerIsoimagesType"
}

func (t ScpServerIsoimagesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	architectureAttribute, ok := attributes["architecture"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`architecture is missing from object`)

		return nil, diags
	}

	architectureVal, ok := architectureAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`architecture expected to be basetypes.StringValue, was: %T`, architectureAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ScpServerIsoimagesValue{
		Architecture: architectureVal,
		Description:  descriptionVal,
		Id:           idVal,
		Name:         nameVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewScpServerIsoimagesValueNull() ScpServerIsoimagesValue {
	return ScpServerIsoimagesValue{
		state: attr.ValueStateNull,
	}
}

func NewScpServerIsoimagesValueUnknown() ScpServerIsoimagesValue {
	return ScpServerIsoimagesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewScpServerIsoimagesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ScpServerIsoimagesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ScpServerIsoimagesValue Attribute Value",
				"While creating a ScpServerIsoimagesValue value, a missing attribute value was detected. "+
					"A ScpServerIsoimagesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScpServerIsoimagesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ScpServerIsoimagesValue Attribute Type",
				"While creating a ScpServerIsoimagesValue value, an invalid attribute value was detected. "+
					"A ScpServerIsoimagesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScpServerIsoimagesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ScpServerIsoimagesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ScpServerIsoimagesValue Attribute Value",
				"While creating a ScpServerIsoimagesValue value, an extra attribute value was detected. "+
					"A ScpServerIsoimagesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ScpServerIsoimagesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewScpServerIsoimagesValueUnknown(), diags
	}

	architectureAttribute, ok := attributes["architecture"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`architecture is missing from object`)

		return NewScpServerIsoimagesValueUnknown(), diags
	}

	architectureVal, ok := architectureAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`architecture expected to be basetypes.StringValue, was: %T`, architectureAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewScpServerIsoimagesValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewScpServerIsoimagesValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewScpServerIsoimagesValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return NewScpServerIsoimagesValueUnknown(), diags
	}

	return ScpServerIsoimagesValue{
		Architecture: architectureVal,
		Description:  descriptionVal,
		Id:           idVal,
		Name:         nameVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewScpServerIsoimagesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ScpServerIsoimagesValue {
	object, diags := NewScpServerIsoimagesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewScpServerIsoimagesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ScpServerIsoimagesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewScpServerIsoimagesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewScpServerIsoimagesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewScpServerIsoimagesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewScpServerIsoimagesValueMust(ScpServerIsoimagesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ScpServerIsoimagesType) ValueType(ctx context.Context) attr.Value {
	return ScpServerIsoimagesValue{}
}

var _ basetypes.ObjectValuable = ScpServerIsoimagesValue{}

type ScpServerIsoimagesValue struct {
	Architecture basetypes.StringValue `tfsdk:"architecture"`
	Description  basetypes.StringValue `tfsdk:"description"`
	Id           basetypes.Int64Value  `tfsdk:"id"`
	Name         basetypes.StringValue `tfsdk:"name"`
	state        attr.ValueState
}

func (v ScpServerIsoimagesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["architecture"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.Architecture.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["architecture"] = val

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ScpServerIsoimagesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ScpServerIsoimagesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ScpServerIsoimagesValue) String() string {
	return "ScpServerIsoimagesValue"
}

func (v ScpServerIsoimagesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"architecture": basetypes.StringType{},
		"description":  basetypes.StringType{},
		"id":           basetypes.Int64Type{},
		"name":         basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"architecture": v.Architecture,
			"description":  v.Description,
			"id":           v.Id,
			"name":         v.Name,
		})

	return objVal, diags
}

func (v ScpServerIsoimagesValue) Equal(o attr.Value) bool {
	other, ok := o.(ScpServerIsoimagesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Architecture.Equal(other.Architecture) {
		return false
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	return true
}

func (v ScpServerIsoimagesValue) Type(ctx context.Context) attr.Type {
	return ScpServerIsoimagesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ScpServerIsoimagesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"architecture": basetypes.StringType{},
		"description":  basetypes.StringType{},
		"id":           basetypes.Int64Type{},
		"name":         basetypes.StringType{},
	}
}
