// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scptask

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpTaskDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"executing_user": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"company": schema.StringAttribute{
						Computed: true,
					},
					"email": schema.StringAttribute{
						Computed: true,
					},
					"firstname": schema.StringAttribute{
						Computed: true,
					},
					"id": schema.Int64Attribute{
						Computed: true,
					},
					"lastname": schema.StringAttribute{
						Computed: true,
					},
					"username": schema.StringAttribute{
						Computed: true,
					},
				},
				CustomType: ExecutingUserType{
					ObjectType: types.ObjectType{
						AttrTypes: ExecutingUserValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"finished_at": schema.StringAttribute{
				Computed: true,
			},
			"message": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"on_rollback": schema.BoolAttribute{
				Computed: true,
			},
			"response_error": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"code": schema.StringAttribute{
						Computed: true,
					},
					"message": schema.StringAttribute{
						Computed: true,
					},
				},
				CustomType: ResponseErrorType{
					ObjectType: types.ObjectType{
						AttrTypes: ResponseErrorValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"result": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{},
				CustomType: ResultType{
					ObjectType: types.ObjectType{
						AttrTypes: ResultValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"started_at": schema.StringAttribute{
				Computed: true,
			},
			"state": schema.StringAttribute{
				Computed: true,
			},
			"steps": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"finished_at": schema.StringAttribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"started_at": schema.StringAttribute{
							Computed: true,
						},
						"state": schema.StringAttribute{
							Computed: true,
						},
						"uuid": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: StepsType{
						ObjectType: types.ObjectType{
							AttrTypes: StepsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"task_progress": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"expected_finished_at": schema.StringAttribute{
						Computed: true,
					},
					"progress_in_percent": schema.Float64Attribute{
						Computed: true,
					},
				},
				CustomType: TaskProgressType{
					ObjectType: types.ObjectType{
						AttrTypes: TaskProgressValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"uuid": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type ScpTaskModel struct {
	ExecutingUser ExecutingUserValue `tfsdk:"executing_user"`
	FinishedAt    types.String       `tfsdk:"finished_at"`
	Message       types.String       `tfsdk:"message"`
	Name          types.String       `tfsdk:"name"`
	OnRollback    types.Bool         `tfsdk:"on_rollback"`
	ResponseError ResponseErrorValue `tfsdk:"response_error"`
	Result        ResultValue        `tfsdk:"result"`
	StartedAt     types.String       `tfsdk:"started_at"`
	State         types.String       `tfsdk:"state"`
	Steps         types.List         `tfsdk:"steps"`
	TaskProgress  TaskProgressValue  `tfsdk:"task_progress"`
	Uuid          types.String       `tfsdk:"uuid"`
}

var _ basetypes.ObjectTypable = ExecutingUserType{}

type ExecutingUserType struct {
	basetypes.ObjectType
}

func (t ExecutingUserType) Equal(o attr.Type) bool {
	other, ok := o.(ExecutingUserType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ExecutingUserType) String() string {
	return "ExecutingUserType"
}

func (t ExecutingUserType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	companyAttribute, ok := attributes["company"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`company is missing from object`)

		return nil, diags
	}

	companyVal, ok := companyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`company expected to be basetypes.StringValue, was: %T`, companyAttribute))
	}

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return nil, diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	firstnameAttribute, ok := attributes["firstname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`firstname is missing from object`)

		return nil, diags
	}

	firstnameVal, ok := firstnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`firstname expected to be basetypes.StringValue, was: %T`, firstnameAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	lastnameAttribute, ok := attributes["lastname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`lastname is missing from object`)

		return nil, diags
	}

	lastnameVal, ok := lastnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`lastname expected to be basetypes.StringValue, was: %T`, lastnameAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return nil, diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ExecutingUserValue{
		Company:   companyVal,
		Email:     emailVal,
		Firstname: firstnameVal,
		Id:        idVal,
		Lastname:  lastnameVal,
		Username:  usernameVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewExecutingUserValueNull() ExecutingUserValue {
	return ExecutingUserValue{
		state: attr.ValueStateNull,
	}
}

func NewExecutingUserValueUnknown() ExecutingUserValue {
	return ExecutingUserValue{
		state: attr.ValueStateUnknown,
	}
}

func NewExecutingUserValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ExecutingUserValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ExecutingUserValue Attribute Value",
				"While creating a ExecutingUserValue value, a missing attribute value was detected. "+
					"A ExecutingUserValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ExecutingUserValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ExecutingUserValue Attribute Type",
				"While creating a ExecutingUserValue value, an invalid attribute value was detected. "+
					"A ExecutingUserValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ExecutingUserValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ExecutingUserValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ExecutingUserValue Attribute Value",
				"While creating a ExecutingUserValue value, an extra attribute value was detected. "+
					"A ExecutingUserValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ExecutingUserValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewExecutingUserValueUnknown(), diags
	}

	companyAttribute, ok := attributes["company"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`company is missing from object`)

		return NewExecutingUserValueUnknown(), diags
	}

	companyVal, ok := companyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`company expected to be basetypes.StringValue, was: %T`, companyAttribute))
	}

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return NewExecutingUserValueUnknown(), diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	firstnameAttribute, ok := attributes["firstname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`firstname is missing from object`)

		return NewExecutingUserValueUnknown(), diags
	}

	firstnameVal, ok := firstnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`firstname expected to be basetypes.StringValue, was: %T`, firstnameAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewExecutingUserValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	lastnameAttribute, ok := attributes["lastname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`lastname is missing from object`)

		return NewExecutingUserValueUnknown(), diags
	}

	lastnameVal, ok := lastnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`lastname expected to be basetypes.StringValue, was: %T`, lastnameAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return NewExecutingUserValueUnknown(), diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	if diags.HasError() {
		return NewExecutingUserValueUnknown(), diags
	}

	return ExecutingUserValue{
		Company:   companyVal,
		Email:     emailVal,
		Firstname: firstnameVal,
		Id:        idVal,
		Lastname:  lastnameVal,
		Username:  usernameVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewExecutingUserValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ExecutingUserValue {
	object, diags := NewExecutingUserValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewExecutingUserValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ExecutingUserType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewExecutingUserValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewExecutingUserValueUnknown(), nil
	}

	if in.IsNull() {
		return NewExecutingUserValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewExecutingUserValueMust(ExecutingUserValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ExecutingUserType) ValueType(ctx context.Context) attr.Value {
	return ExecutingUserValue{}
}

var _ basetypes.ObjectValuable = ExecutingUserValue{}

type ExecutingUserValue struct {
	Company   basetypes.StringValue `tfsdk:"company"`
	Email     basetypes.StringValue `tfsdk:"email"`
	Firstname basetypes.StringValue `tfsdk:"firstname"`
	Id        basetypes.Int64Value  `tfsdk:"id"`
	Lastname  basetypes.StringValue `tfsdk:"lastname"`
	Username  basetypes.StringValue `tfsdk:"username"`
	state     attr.ValueState
}

func (v ExecutingUserValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["company"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["email"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["firstname"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["lastname"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["username"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.Company.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["company"] = val

		val, err = v.Email.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["email"] = val

		val, err = v.Firstname.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["firstname"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Lastname.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["lastname"] = val

		val, err = v.Username.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["username"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ExecutingUserValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ExecutingUserValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ExecutingUserValue) String() string {
	return "ExecutingUserValue"
}

func (v ExecutingUserValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"company":   basetypes.StringType{},
		"email":     basetypes.StringType{},
		"firstname": basetypes.StringType{},
		"id":        basetypes.Int64Type{},
		"lastname":  basetypes.StringType{},
		"username":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"company":   v.Company,
			"email":     v.Email,
			"firstname": v.Firstname,
			"id":        v.Id,
			"lastname":  v.Lastname,
			"username":  v.Username,
		})

	return objVal, diags
}

func (v ExecutingUserValue) Equal(o attr.Value) bool {
	other, ok := o.(ExecutingUserValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Company.Equal(other.Company) {
		return false
	}

	if !v.Email.Equal(other.Email) {
		return false
	}

	if !v.Firstname.Equal(other.Firstname) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Lastname.Equal(other.Lastname) {
		return false
	}

	if !v.Username.Equal(other.Username) {
		return false
	}

	return true
}

func (v ExecutingUserValue) Type(ctx context.Context) attr.Type {
	return ExecutingUserType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ExecutingUserValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"company":   basetypes.StringType{},
		"email":     basetypes.StringType{},
		"firstname": basetypes.StringType{},
		"id":        basetypes.Int64Type{},
		"lastname":  basetypes.StringType{},
		"username":  basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ResponseErrorType{}

type ResponseErrorType struct {
	basetypes.ObjectType
}

func (t ResponseErrorType) Equal(o attr.Type) bool {
	other, ok := o.(ResponseErrorType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ResponseErrorType) String() string {
	return "ResponseErrorType"
}

func (t ResponseErrorType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	codeAttribute, ok := attributes["code"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`code is missing from object`)

		return nil, diags
	}

	codeVal, ok := codeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`code expected to be basetypes.StringValue, was: %T`, codeAttribute))
	}

	messageAttribute, ok := attributes["message"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`message is missing from object`)

		return nil, diags
	}

	messageVal, ok := messageAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`message expected to be basetypes.StringValue, was: %T`, messageAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ResponseErrorValue{
		Code:    codeVal,
		Message: messageVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewResponseErrorValueNull() ResponseErrorValue {
	return ResponseErrorValue{
		state: attr.ValueStateNull,
	}
}

func NewResponseErrorValueUnknown() ResponseErrorValue {
	return ResponseErrorValue{
		state: attr.ValueStateUnknown,
	}
}

func NewResponseErrorValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ResponseErrorValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ResponseErrorValue Attribute Value",
				"While creating a ResponseErrorValue value, a missing attribute value was detected. "+
					"A ResponseErrorValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResponseErrorValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ResponseErrorValue Attribute Type",
				"While creating a ResponseErrorValue value, an invalid attribute value was detected. "+
					"A ResponseErrorValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResponseErrorValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ResponseErrorValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ResponseErrorValue Attribute Value",
				"While creating a ResponseErrorValue value, an extra attribute value was detected. "+
					"A ResponseErrorValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ResponseErrorValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewResponseErrorValueUnknown(), diags
	}

	codeAttribute, ok := attributes["code"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`code is missing from object`)

		return NewResponseErrorValueUnknown(), diags
	}

	codeVal, ok := codeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`code expected to be basetypes.StringValue, was: %T`, codeAttribute))
	}

	messageAttribute, ok := attributes["message"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`message is missing from object`)

		return NewResponseErrorValueUnknown(), diags
	}

	messageVal, ok := messageAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`message expected to be basetypes.StringValue, was: %T`, messageAttribute))
	}

	if diags.HasError() {
		return NewResponseErrorValueUnknown(), diags
	}

	return ResponseErrorValue{
		Code:    codeVal,
		Message: messageVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewResponseErrorValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ResponseErrorValue {
	object, diags := NewResponseErrorValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewResponseErrorValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ResponseErrorType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewResponseErrorValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewResponseErrorValueUnknown(), nil
	}

	if in.IsNull() {
		return NewResponseErrorValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewResponseErrorValueMust(ResponseErrorValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ResponseErrorType) ValueType(ctx context.Context) attr.Value {
	return ResponseErrorValue{}
}

var _ basetypes.ObjectValuable = ResponseErrorValue{}

type ResponseErrorValue struct {
	Code    basetypes.StringValue `tfsdk:"code"`
	Message basetypes.StringValue `tfsdk:"message"`
	state   attr.ValueState
}

func (v ResponseErrorValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["code"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["message"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Code.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["code"] = val

		val, err = v.Message.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["message"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ResponseErrorValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ResponseErrorValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ResponseErrorValue) String() string {
	return "ResponseErrorValue"
}

func (v ResponseErrorValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"code":    basetypes.StringType{},
		"message": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"code":    v.Code,
			"message": v.Message,
		})

	return objVal, diags
}

func (v ResponseErrorValue) Equal(o attr.Value) bool {
	other, ok := o.(ResponseErrorValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Code.Equal(other.Code) {
		return false
	}

	if !v.Message.Equal(other.Message) {
		return false
	}

	return true
}

func (v ResponseErrorValue) Type(ctx context.Context) attr.Type {
	return ResponseErrorType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ResponseErrorValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"code":    basetypes.StringType{},
		"message": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ResultType{}

type ResultType struct {
	basetypes.ObjectType
}

func (t ResultType) Equal(o attr.Type) bool {
	other, ok := o.(ResultType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ResultType) String() string {
	return "ResultType"
}

func (t ResultType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if diags.HasError() {
		return nil, diags
	}

	return ResultValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewResultValueNull() ResultValue {
	return ResultValue{
		state: attr.ValueStateNull,
	}
}

func NewResultValueUnknown() ResultValue {
	return ResultValue{
		state: attr.ValueStateUnknown,
	}
}

func NewResultValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ResultValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ResultValue Attribute Value",
				"While creating a ResultValue value, a missing attribute value was detected. "+
					"A ResultValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResultValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ResultValue Attribute Type",
				"While creating a ResultValue value, an invalid attribute value was detected. "+
					"A ResultValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResultValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ResultValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ResultValue Attribute Value",
				"While creating a ResultValue value, an extra attribute value was detected. "+
					"A ResultValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ResultValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewResultValueUnknown(), diags
	}

	if diags.HasError() {
		return NewResultValueUnknown(), diags
	}

	return ResultValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewResultValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ResultValue {
	object, diags := NewResultValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewResultValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ResultType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewResultValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewResultValueUnknown(), nil
	}

	if in.IsNull() {
		return NewResultValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewResultValueMust(ResultValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ResultType) ValueType(ctx context.Context) attr.Value {
	return ResultValue{}
}

var _ basetypes.ObjectValuable = ResultValue{}

type ResultValue struct {
	state attr.ValueState
}

func (v ResultValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 0)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 0)

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ResultValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ResultValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ResultValue) String() string {
	return "ResultValue"
}

func (v ResultValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{})

	return objVal, diags
}

func (v ResultValue) Equal(o attr.Value) bool {
	other, ok := o.(ResultValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	return true
}

func (v ResultValue) Type(ctx context.Context) attr.Type {
	return ResultType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ResultValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{}
}

var _ basetypes.ObjectTypable = StepsType{}

type StepsType struct {
	basetypes.ObjectType
}

func (t StepsType) Equal(o attr.Type) bool {
	other, ok := o.(StepsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t StepsType) String() string {
	return "StepsType"
}

func (t StepsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	finishedAtAttribute, ok := attributes["finished_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`finished_at is missing from object`)

		return nil, diags
	}

	finishedAtVal, ok := finishedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`finished_at expected to be basetypes.StringValue, was: %T`, finishedAtAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	startedAtAttribute, ok := attributes["started_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`started_at is missing from object`)

		return nil, diags
	}

	startedAtVal, ok := startedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`started_at expected to be basetypes.StringValue, was: %T`, startedAtAttribute))
	}

	stateAttribute, ok := attributes["state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state is missing from object`)

		return nil, diags
	}

	stateVal, ok := stateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state expected to be basetypes.StringValue, was: %T`, stateAttribute))
	}

	uuidAttribute, ok := attributes["uuid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uuid is missing from object`)

		return nil, diags
	}

	uuidVal, ok := uuidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uuid expected to be basetypes.StringValue, was: %T`, uuidAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return StepsValue{
		FinishedAt: finishedAtVal,
		Name:       nameVal,
		StartedAt:  startedAtVal,
		State:      stateVal,
		Uuid:       uuidVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewStepsValueNull() StepsValue {
	return StepsValue{
		state: attr.ValueStateNull,
	}
}

func NewStepsValueUnknown() StepsValue {
	return StepsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewStepsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (StepsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing StepsValue Attribute Value",
				"While creating a StepsValue value, a missing attribute value was detected. "+
					"A StepsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("StepsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid StepsValue Attribute Type",
				"While creating a StepsValue value, an invalid attribute value was detected. "+
					"A StepsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("StepsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("StepsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra StepsValue Attribute Value",
				"While creating a StepsValue value, an extra attribute value was detected. "+
					"A StepsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra StepsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewStepsValueUnknown(), diags
	}

	finishedAtAttribute, ok := attributes["finished_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`finished_at is missing from object`)

		return NewStepsValueUnknown(), diags
	}

	finishedAtVal, ok := finishedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`finished_at expected to be basetypes.StringValue, was: %T`, finishedAtAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewStepsValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	startedAtAttribute, ok := attributes["started_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`started_at is missing from object`)

		return NewStepsValueUnknown(), diags
	}

	startedAtVal, ok := startedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`started_at expected to be basetypes.StringValue, was: %T`, startedAtAttribute))
	}

	stateAttribute, ok := attributes["state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state is missing from object`)

		return NewStepsValueUnknown(), diags
	}

	stateVal, ok := stateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state expected to be basetypes.StringValue, was: %T`, stateAttribute))
	}

	uuidAttribute, ok := attributes["uuid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uuid is missing from object`)

		return NewStepsValueUnknown(), diags
	}

	uuidVal, ok := uuidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uuid expected to be basetypes.StringValue, was: %T`, uuidAttribute))
	}

	if diags.HasError() {
		return NewStepsValueUnknown(), diags
	}

	return StepsValue{
		FinishedAt: finishedAtVal,
		Name:       nameVal,
		StartedAt:  startedAtVal,
		State:      stateVal,
		Uuid:       uuidVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewStepsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) StepsValue {
	object, diags := NewStepsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewStepsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t StepsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewStepsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewStepsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewStepsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewStepsValueMust(StepsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t StepsType) ValueType(ctx context.Context) attr.Value {
	return StepsValue{}
}

var _ basetypes.ObjectValuable = StepsValue{}

type StepsValue struct {
	FinishedAt basetypes.StringValue `tfsdk:"finished_at"`
	Name       basetypes.StringValue `tfsdk:"name"`
	StartedAt  basetypes.StringValue `tfsdk:"started_at"`
	State      basetypes.StringValue `tfsdk:"state"`
	Uuid       basetypes.StringValue `tfsdk:"uuid"`
	state      attr.ValueState
}

func (v StepsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["finished_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["started_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["state"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["uuid"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.FinishedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["finished_at"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.StartedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["started_at"] = val

		val, err = v.State.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["state"] = val

		val, err = v.Uuid.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["uuid"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v StepsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v StepsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v StepsValue) String() string {
	return "StepsValue"
}

func (v StepsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"finished_at": basetypes.StringType{},
		"name":        basetypes.StringType{},
		"started_at":  basetypes.StringType{},
		"state":       basetypes.StringType{},
		"uuid":        basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"finished_at": v.FinishedAt,
			"name":        v.Name,
			"started_at":  v.StartedAt,
			"state":       v.State,
			"uuid":        v.Uuid,
		})

	return objVal, diags
}

func (v StepsValue) Equal(o attr.Value) bool {
	other, ok := o.(StepsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.FinishedAt.Equal(other.FinishedAt) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.StartedAt.Equal(other.StartedAt) {
		return false
	}

	if !v.State.Equal(other.State) {
		return false
	}

	if !v.Uuid.Equal(other.Uuid) {
		return false
	}

	return true
}

func (v StepsValue) Type(ctx context.Context) attr.Type {
	return StepsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v StepsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"finished_at": basetypes.StringType{},
		"name":        basetypes.StringType{},
		"started_at":  basetypes.StringType{},
		"state":       basetypes.StringType{},
		"uuid":        basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = TaskProgressType{}

type TaskProgressType struct {
	basetypes.ObjectType
}

func (t TaskProgressType) Equal(o attr.Type) bool {
	other, ok := o.(TaskProgressType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TaskProgressType) String() string {
	return "TaskProgressType"
}

func (t TaskProgressType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	expectedFinishedAtAttribute, ok := attributes["expected_finished_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`expected_finished_at is missing from object`)

		return nil, diags
	}

	expectedFinishedAtVal, ok := expectedFinishedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`expected_finished_at expected to be basetypes.StringValue, was: %T`, expectedFinishedAtAttribute))
	}

	progressInPercentAttribute, ok := attributes["progress_in_percent"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`progress_in_percent is missing from object`)

		return nil, diags
	}

	progressInPercentVal, ok := progressInPercentAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`progress_in_percent expected to be basetypes.Float64Value, was: %T`, progressInPercentAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TaskProgressValue{
		ExpectedFinishedAt: expectedFinishedAtVal,
		ProgressInPercent:  progressInPercentVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewTaskProgressValueNull() TaskProgressValue {
	return TaskProgressValue{
		state: attr.ValueStateNull,
	}
}

func NewTaskProgressValueUnknown() TaskProgressValue {
	return TaskProgressValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTaskProgressValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TaskProgressValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TaskProgressValue Attribute Value",
				"While creating a TaskProgressValue value, a missing attribute value was detected. "+
					"A TaskProgressValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TaskProgressValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TaskProgressValue Attribute Type",
				"While creating a TaskProgressValue value, an invalid attribute value was detected. "+
					"A TaskProgressValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TaskProgressValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TaskProgressValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TaskProgressValue Attribute Value",
				"While creating a TaskProgressValue value, an extra attribute value was detected. "+
					"A TaskProgressValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TaskProgressValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTaskProgressValueUnknown(), diags
	}

	expectedFinishedAtAttribute, ok := attributes["expected_finished_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`expected_finished_at is missing from object`)

		return NewTaskProgressValueUnknown(), diags
	}

	expectedFinishedAtVal, ok := expectedFinishedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`expected_finished_at expected to be basetypes.StringValue, was: %T`, expectedFinishedAtAttribute))
	}

	progressInPercentAttribute, ok := attributes["progress_in_percent"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`progress_in_percent is missing from object`)

		return NewTaskProgressValueUnknown(), diags
	}

	progressInPercentVal, ok := progressInPercentAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`progress_in_percent expected to be basetypes.Float64Value, was: %T`, progressInPercentAttribute))
	}

	if diags.HasError() {
		return NewTaskProgressValueUnknown(), diags
	}

	return TaskProgressValue{
		ExpectedFinishedAt: expectedFinishedAtVal,
		ProgressInPercent:  progressInPercentVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewTaskProgressValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TaskProgressValue {
	object, diags := NewTaskProgressValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTaskProgressValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TaskProgressType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTaskProgressValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTaskProgressValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTaskProgressValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTaskProgressValueMust(TaskProgressValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TaskProgressType) ValueType(ctx context.Context) attr.Value {
	return TaskProgressValue{}
}

var _ basetypes.ObjectValuable = TaskProgressValue{}

type TaskProgressValue struct {
	ExpectedFinishedAt basetypes.StringValue  `tfsdk:"expected_finished_at"`
	ProgressInPercent  basetypes.Float64Value `tfsdk:"progress_in_percent"`
	state              attr.ValueState
}

func (v TaskProgressValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["expected_finished_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["progress_in_percent"] = basetypes.Float64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.ExpectedFinishedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["expected_finished_at"] = val

		val, err = v.ProgressInPercent.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["progress_in_percent"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TaskProgressValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TaskProgressValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TaskProgressValue) String() string {
	return "TaskProgressValue"
}

func (v TaskProgressValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"expected_finished_at": basetypes.StringType{},
		"progress_in_percent":  basetypes.Float64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"expected_finished_at": v.ExpectedFinishedAt,
			"progress_in_percent":  v.ProgressInPercent,
		})

	return objVal, diags
}

func (v TaskProgressValue) Equal(o attr.Value) bool {
	other, ok := o.(TaskProgressValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ExpectedFinishedAt.Equal(other.ExpectedFinishedAt) {
		return false
	}

	if !v.ProgressInPercent.Equal(other.ProgressInPercent) {
		return false
	}

	return true
}

func (v TaskProgressValue) Type(ctx context.Context) attr.Type {
	return TaskProgressType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TaskProgressValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"expected_finished_at": basetypes.StringType{},
		"progress_in_percent":  basetypes.Float64Type{},
	}
}
