// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scpserverrescuesystem

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpServerRescuesystemDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"active": schema.BoolAttribute{
				Computed: true,
			},
			"password": schema.StringAttribute{
				Computed: true,
			},
			"server_id": schema.Int64Attribute{
				Required: true,
			},
		},
	}
}

type ScpServerRescuesystemModel struct {
	Active   types.Bool   `tfsdk:"active"`
	Password types.String `tfsdk:"password"`
	ServerId types.Int64  `tfsdk:"server_id"`
}
