// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scpmaintenance

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpMaintenanceDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"finish_at": schema.StringAttribute{
				Computed: true,
			},
			"start_at": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type ScpMaintenanceModel struct {
	FinishAt types.String `tfsdk:"finish_at"`
	StartAt  types.String `tfsdk:"start_at"`
}
