// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scpserversnapshots

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpServerSnapshotsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		MarkdownDescription: "Get all snapshots of a server.",
		Attributes: map[string]schema.Attribute{
			"scp_server_snapshots": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"creation_time": schema.StringAttribute{
							Computed: true,
						},
						"description": schema.StringAttribute{
							Computed: true,
						},
						"disks": schema.ListAttribute{
							ElementType: types.StringType,
							Computed:    true,
						},
						"exported": schema.BoolAttribute{
							Computed: true,
						},
						"exported_size_in_ki_b": schema.Int64Attribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"online": schema.BoolAttribute{
							Computed: true,
						},
						"state": schema.StringAttribute{
							Computed: true,
						},
						"uuid": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: ScpServerSnapshotsType{
						ObjectType: types.ObjectType{
							AttrTypes: ScpServerSnapshotsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"server_id": schema.Int64Attribute{
				Required: true,
			},
		},
	}
}

type ScpServerSnapshotsModel struct {
	ScpServerSnapshots types.Set   `tfsdk:"scp_server_snapshots"`
	ServerId           types.Int64 `tfsdk:"server_id"`
}

var _ basetypes.ObjectTypable = ScpServerSnapshotsType{}

type ScpServerSnapshotsType struct {
	basetypes.ObjectType
}

func (t ScpServerSnapshotsType) Equal(o attr.Type) bool {
	other, ok := o.(ScpServerSnapshotsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ScpServerSnapshotsType) String() string {
	return "ScpServerSnapshotsType"
}

func (t ScpServerSnapshotsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	creationTimeAttribute, ok := attributes["creation_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`creation_time is missing from object`)

		return nil, diags
	}

	creationTimeVal, ok := creationTimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`creation_time expected to be basetypes.StringValue, was: %T`, creationTimeAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	disksAttribute, ok := attributes["disks"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`disks is missing from object`)

		return nil, diags
	}

	disksVal, ok := disksAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`disks expected to be basetypes.ListValue, was: %T`, disksAttribute))
	}

	exportedAttribute, ok := attributes["exported"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`exported is missing from object`)

		return nil, diags
	}

	exportedVal, ok := exportedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`exported expected to be basetypes.BoolValue, was: %T`, exportedAttribute))
	}

	exportedSizeInKiBAttribute, ok := attributes["exported_size_in_ki_b"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`exported_size_in_ki_b is missing from object`)

		return nil, diags
	}

	exportedSizeInKiBVal, ok := exportedSizeInKiBAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`exported_size_in_ki_b expected to be basetypes.Int64Value, was: %T`, exportedSizeInKiBAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	onlineAttribute, ok := attributes["online"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`online is missing from object`)

		return nil, diags
	}

	onlineVal, ok := onlineAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`online expected to be basetypes.BoolValue, was: %T`, onlineAttribute))
	}

	stateAttribute, ok := attributes["state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state is missing from object`)

		return nil, diags
	}

	stateVal, ok := stateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state expected to be basetypes.StringValue, was: %T`, stateAttribute))
	}

	uuidAttribute, ok := attributes["uuid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uuid is missing from object`)

		return nil, diags
	}

	uuidVal, ok := uuidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uuid expected to be basetypes.StringValue, was: %T`, uuidAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ScpServerSnapshotsValue{
		CreationTime:      creationTimeVal,
		Description:       descriptionVal,
		Disks:             disksVal,
		Exported:          exportedVal,
		ExportedSizeInKiB: exportedSizeInKiBVal,
		Name:              nameVal,
		Online:            onlineVal,
		State:             stateVal,
		Uuid:              uuidVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewScpServerSnapshotsValueNull() ScpServerSnapshotsValue {
	return ScpServerSnapshotsValue{
		state: attr.ValueStateNull,
	}
}

func NewScpServerSnapshotsValueUnknown() ScpServerSnapshotsValue {
	return ScpServerSnapshotsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewScpServerSnapshotsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ScpServerSnapshotsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ScpServerSnapshotsValue Attribute Value",
				"While creating a ScpServerSnapshotsValue value, a missing attribute value was detected. "+
					"A ScpServerSnapshotsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScpServerSnapshotsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ScpServerSnapshotsValue Attribute Type",
				"While creating a ScpServerSnapshotsValue value, an invalid attribute value was detected. "+
					"A ScpServerSnapshotsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScpServerSnapshotsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ScpServerSnapshotsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ScpServerSnapshotsValue Attribute Value",
				"While creating a ScpServerSnapshotsValue value, an extra attribute value was detected. "+
					"A ScpServerSnapshotsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ScpServerSnapshotsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewScpServerSnapshotsValueUnknown(), diags
	}

	creationTimeAttribute, ok := attributes["creation_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`creation_time is missing from object`)

		return NewScpServerSnapshotsValueUnknown(), diags
	}

	creationTimeVal, ok := creationTimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`creation_time expected to be basetypes.StringValue, was: %T`, creationTimeAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewScpServerSnapshotsValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	disksAttribute, ok := attributes["disks"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`disks is missing from object`)

		return NewScpServerSnapshotsValueUnknown(), diags
	}

	disksVal, ok := disksAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`disks expected to be basetypes.ListValue, was: %T`, disksAttribute))
	}

	exportedAttribute, ok := attributes["exported"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`exported is missing from object`)

		return NewScpServerSnapshotsValueUnknown(), diags
	}

	exportedVal, ok := exportedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`exported expected to be basetypes.BoolValue, was: %T`, exportedAttribute))
	}

	exportedSizeInKiBAttribute, ok := attributes["exported_size_in_ki_b"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`exported_size_in_ki_b is missing from object`)

		return NewScpServerSnapshotsValueUnknown(), diags
	}

	exportedSizeInKiBVal, ok := exportedSizeInKiBAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`exported_size_in_ki_b expected to be basetypes.Int64Value, was: %T`, exportedSizeInKiBAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewScpServerSnapshotsValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	onlineAttribute, ok := attributes["online"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`online is missing from object`)

		return NewScpServerSnapshotsValueUnknown(), diags
	}

	onlineVal, ok := onlineAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`online expected to be basetypes.BoolValue, was: %T`, onlineAttribute))
	}

	stateAttribute, ok := attributes["state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state is missing from object`)

		return NewScpServerSnapshotsValueUnknown(), diags
	}

	stateVal, ok := stateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state expected to be basetypes.StringValue, was: %T`, stateAttribute))
	}

	uuidAttribute, ok := attributes["uuid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uuid is missing from object`)

		return NewScpServerSnapshotsValueUnknown(), diags
	}

	uuidVal, ok := uuidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uuid expected to be basetypes.StringValue, was: %T`, uuidAttribute))
	}

	if diags.HasError() {
		return NewScpServerSnapshotsValueUnknown(), diags
	}

	return ScpServerSnapshotsValue{
		CreationTime:      creationTimeVal,
		Description:       descriptionVal,
		Disks:             disksVal,
		Exported:          exportedVal,
		ExportedSizeInKiB: exportedSizeInKiBVal,
		Name:              nameVal,
		Online:            onlineVal,
		State:             stateVal,
		Uuid:              uuidVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewScpServerSnapshotsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ScpServerSnapshotsValue {
	object, diags := NewScpServerSnapshotsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewScpServerSnapshotsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ScpServerSnapshotsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewScpServerSnapshotsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewScpServerSnapshotsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewScpServerSnapshotsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewScpServerSnapshotsValueMust(ScpServerSnapshotsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ScpServerSnapshotsType) ValueType(ctx context.Context) attr.Value {
	return ScpServerSnapshotsValue{}
}

var _ basetypes.ObjectValuable = ScpServerSnapshotsValue{}

type ScpServerSnapshotsValue struct {
	CreationTime      basetypes.StringValue `tfsdk:"creation_time"`
	Description       basetypes.StringValue `tfsdk:"description"`
	Disks             basetypes.ListValue   `tfsdk:"disks"`
	Exported          basetypes.BoolValue   `tfsdk:"exported"`
	ExportedSizeInKiB basetypes.Int64Value  `tfsdk:"exported_size_in_ki_b"`
	Name              basetypes.StringValue `tfsdk:"name"`
	Online            basetypes.BoolValue   `tfsdk:"online"`
	State             basetypes.StringValue `tfsdk:"state"`
	Uuid              basetypes.StringValue `tfsdk:"uuid"`
	state             attr.ValueState
}

func (v ScpServerSnapshotsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 9)

	var val tftypes.Value
	var err error

	attrTypes["creation_time"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["disks"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["exported"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["exported_size_in_ki_b"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["online"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["state"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["uuid"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 9)

		val, err = v.CreationTime.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["creation_time"] = val

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.Disks.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["disks"] = val

		val, err = v.Exported.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["exported"] = val

		val, err = v.ExportedSizeInKiB.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["exported_size_in_ki_b"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Online.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["online"] = val

		val, err = v.State.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["state"] = val

		val, err = v.Uuid.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["uuid"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ScpServerSnapshotsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ScpServerSnapshotsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ScpServerSnapshotsValue) String() string {
	return "ScpServerSnapshotsValue"
}

func (v ScpServerSnapshotsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var disksVal basetypes.ListValue
	switch {
	case v.Disks.IsUnknown():
		disksVal = types.ListUnknown(types.StringType)
	case v.Disks.IsNull():
		disksVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		disksVal, d = types.ListValue(types.StringType, v.Disks.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"creation_time": basetypes.StringType{},
			"description":   basetypes.StringType{},
			"disks": basetypes.ListType{
				ElemType: types.StringType,
			},
			"exported":              basetypes.BoolType{},
			"exported_size_in_ki_b": basetypes.Int64Type{},
			"name":                  basetypes.StringType{},
			"online":                basetypes.BoolType{},
			"state":                 basetypes.StringType{},
			"uuid":                  basetypes.StringType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"creation_time": basetypes.StringType{},
		"description":   basetypes.StringType{},
		"disks": basetypes.ListType{
			ElemType: types.StringType,
		},
		"exported":              basetypes.BoolType{},
		"exported_size_in_ki_b": basetypes.Int64Type{},
		"name":                  basetypes.StringType{},
		"online":                basetypes.BoolType{},
		"state":                 basetypes.StringType{},
		"uuid":                  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"creation_time":         v.CreationTime,
			"description":           v.Description,
			"disks":                 disksVal,
			"exported":              v.Exported,
			"exported_size_in_ki_b": v.ExportedSizeInKiB,
			"name":                  v.Name,
			"online":                v.Online,
			"state":                 v.State,
			"uuid":                  v.Uuid,
		})

	return objVal, diags
}

func (v ScpServerSnapshotsValue) Equal(o attr.Value) bool {
	other, ok := o.(ScpServerSnapshotsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CreationTime.Equal(other.CreationTime) {
		return false
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.Disks.Equal(other.Disks) {
		return false
	}

	if !v.Exported.Equal(other.Exported) {
		return false
	}

	if !v.ExportedSizeInKiB.Equal(other.ExportedSizeInKiB) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Online.Equal(other.Online) {
		return false
	}

	if !v.State.Equal(other.State) {
		return false
	}

	if !v.Uuid.Equal(other.Uuid) {
		return false
	}

	return true
}

func (v ScpServerSnapshotsValue) Type(ctx context.Context) attr.Type {
	return ScpServerSnapshotsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ScpServerSnapshotsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"creation_time": basetypes.StringType{},
		"description":   basetypes.StringType{},
		"disks": basetypes.ListType{
			ElemType: types.StringType,
		},
		"exported":              basetypes.BoolType{},
		"exported_size_in_ki_b": basetypes.Int64Type{},
		"name":                  basetypes.StringType{},
		"online":                basetypes.BoolType{},
		"state":                 basetypes.StringType{},
		"uuid":                  basetypes.StringType{},
	}
}
