// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scpuserimagepart

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpUserImagePartDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"key": schema.StringAttribute{
				Required: true,
			},
			"part_number": schema.Int64Attribute{
				Required: true,
			},
			"upload_id": schema.StringAttribute{
				Required: true,
			},
			"url": schema.StringAttribute{
				Computed: true,
			},
			"user_id": schema.Int64Attribute{
				Required: true,
			},
		},
	}
}

type ScpUserImagePartModel struct {
	Key        types.String `tfsdk:"key"`
	PartNumber types.Int64  `tfsdk:"part_number"`
	UploadId   types.String `tfsdk:"upload_id"`
	Url        types.String `tfsdk:"url"`
	UserId     types.Int64  `tfsdk:"user_id"`
}
