// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scpuser

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpUserDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		MarkdownDescription: "Get one user",
		Attributes: map[string]schema.Attribute{
			"api_ip_login_restrictions": schema.StringAttribute{
				Computed: true,
			},
			"company": schema.StringAttribute{
				Computed: true,
			},
			"email": schema.StringAttribute{
				Computed: true,
			},
			"firstname": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.Int64Attribute{
				Computed: true,
			},
			"language": schema.StringAttribute{
				Computed: true,
			},
			"lastname": schema.StringAttribute{
				Computed: true,
			},
			"passwordless_mode": schema.BoolAttribute{
				Computed: true,
			},
			"secure_mode": schema.BoolAttribute{
				Computed: true,
			},
			"show_nickname": schema.BoolAttribute{
				Computed: true,
			},
			"time_zone": schema.StringAttribute{
				Computed: true,
			},
			"user_id": schema.Int64Attribute{
				Required: true,
			},
			"username": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type ScpUserModel struct {
	ApiIpLoginRestrictions types.String `tfsdk:"api_ip_login_restrictions"`
	Company                types.String `tfsdk:"company"`
	Email                  types.String `tfsdk:"email"`
	Firstname              types.String `tfsdk:"firstname"`
	Id                     types.Int64  `tfsdk:"id"`
	Language               types.String `tfsdk:"language"`
	Lastname               types.String `tfsdk:"lastname"`
	PasswordlessMode       types.Bool   `tfsdk:"passwordless_mode"`
	SecureMode             types.Bool   `tfsdk:"secure_mode"`
	ShowNickname           types.Bool   `tfsdk:"show_nickname"`
	TimeZone               types.String `tfsdk:"time_zone"`
	UserId                 types.Int64  `tfsdk:"user_id"`
	Username               types.String `tfsdk:"username"`
}
