// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scpserverguestagentstatus

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpServerGuestAgentStatusDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"available": schema.BoolAttribute{
				Computed: true,
			},
			"server_id": schema.Int64Attribute{
				Required:            true,
				Description:         "Server id",
				MarkdownDescription: "Server id",
			},
		},
	}
}

type ScpServerGuestAgentStatusModel struct {
	Available types.Bool  `tfsdk:"available"`
	ServerId  types.Int64 `tfsdk:"server_id"`
}
