// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scpserverguestagent

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpServerGuestAgentDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		MarkdownDescription: "Get guest agent data for server",
		Attributes: map[string]schema.Attribute{
			"guest_agent_available": schema.BoolAttribute{
				Computed: true,
			},
			"guest_agent_data": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{},
				CustomType: GuestAgentDataType{
					ObjectType: types.ObjectType{
						AttrTypes: GuestAgentDataValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Information in json format about the qemu guest agent, which may change depending on the version. We do not guarantee backwards compatibility for this data.",
				MarkdownDescription: "Information in json format about the qemu guest agent, which may change depending on the version. We do not guarantee backwards compatibility for this data.",
			},
			"server_id": schema.Int64Attribute{
				Required:            true,
				Description:         "Server id",
				MarkdownDescription: "Server id",
			},
		},
	}
}

type ScpServerGuestAgentModel struct {
	GuestAgentAvailable types.Bool          `tfsdk:"guest_agent_available"`
	GuestAgentData      GuestAgentDataValue `tfsdk:"guest_agent_data"`
	ServerId            types.Int64         `tfsdk:"server_id"`
}

var _ basetypes.ObjectTypable = GuestAgentDataType{}

type GuestAgentDataType struct {
	basetypes.ObjectType
}

func (t GuestAgentDataType) Equal(o attr.Type) bool {
	other, ok := o.(GuestAgentDataType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t GuestAgentDataType) String() string {
	return "GuestAgentDataType"
}

func (t GuestAgentDataType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if diags.HasError() {
		return nil, diags
	}

	return GuestAgentDataValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewGuestAgentDataValueNull() GuestAgentDataValue {
	return GuestAgentDataValue{
		state: attr.ValueStateNull,
	}
}

func NewGuestAgentDataValueUnknown() GuestAgentDataValue {
	return GuestAgentDataValue{
		state: attr.ValueStateUnknown,
	}
}

func NewGuestAgentDataValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (GuestAgentDataValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing GuestAgentDataValue Attribute Value",
				"While creating a GuestAgentDataValue value, a missing attribute value was detected. "+
					"A GuestAgentDataValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("GuestAgentDataValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid GuestAgentDataValue Attribute Type",
				"While creating a GuestAgentDataValue value, an invalid attribute value was detected. "+
					"A GuestAgentDataValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("GuestAgentDataValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("GuestAgentDataValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra GuestAgentDataValue Attribute Value",
				"While creating a GuestAgentDataValue value, an extra attribute value was detected. "+
					"A GuestAgentDataValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra GuestAgentDataValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewGuestAgentDataValueUnknown(), diags
	}

	if diags.HasError() {
		return NewGuestAgentDataValueUnknown(), diags
	}

	return GuestAgentDataValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewGuestAgentDataValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) GuestAgentDataValue {
	object, diags := NewGuestAgentDataValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewGuestAgentDataValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t GuestAgentDataType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewGuestAgentDataValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewGuestAgentDataValueUnknown(), nil
	}

	if in.IsNull() {
		return NewGuestAgentDataValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewGuestAgentDataValueMust(GuestAgentDataValue{}.AttributeTypes(ctx), attributes), nil
}

func (t GuestAgentDataType) ValueType(ctx context.Context) attr.Value {
	return GuestAgentDataValue{}
}

var _ basetypes.ObjectValuable = GuestAgentDataValue{}

type GuestAgentDataValue struct {
	state attr.ValueState
}

func (v GuestAgentDataValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 0)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 0)

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v GuestAgentDataValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v GuestAgentDataValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v GuestAgentDataValue) String() string {
	return "GuestAgentDataValue"
}

func (v GuestAgentDataValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{})

	return objVal, diags
}

func (v GuestAgentDataValue) Equal(o attr.Value) bool {
	other, ok := o.(GuestAgentDataValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	return true
}

func (v GuestAgentDataValue) Type(ctx context.Context) attr.Type {
	return GuestAgentDataType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v GuestAgentDataValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{}
}
