// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package scpuserisos

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ScpUserIsosDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		MarkdownDescription: "Get all available ISOs",
		Attributes: map[string]schema.Attribute{
			"scp_user_isos": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"key": schema.StringAttribute{
							Computed: true,
						},
						"last_modified": schema.StringAttribute{
							Computed: true,
						},
						"size_in_b": schema.Int64Attribute{
							Computed: true,
						},
					},
					CustomType: ScpUserIsosType{
						ObjectType: types.ObjectType{
							AttrTypes: ScpUserIsosValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"user_id": schema.Int64Attribute{
				Required: true,
			},
		},
	}
}

type ScpUserIsosModel struct {
	ScpUserIsos types.Set   `tfsdk:"scp_user_isos"`
	UserId      types.Int64 `tfsdk:"user_id"`
}

var _ basetypes.ObjectTypable = ScpUserIsosType{}

type ScpUserIsosType struct {
	basetypes.ObjectType
}

func (t ScpUserIsosType) Equal(o attr.Type) bool {
	other, ok := o.(ScpUserIsosType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ScpUserIsosType) String() string {
	return "ScpUserIsosType"
}

func (t ScpUserIsosType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return nil, diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	lastModifiedAttribute, ok := attributes["last_modified"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_modified is missing from object`)

		return nil, diags
	}

	lastModifiedVal, ok := lastModifiedAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_modified expected to be basetypes.StringValue, was: %T`, lastModifiedAttribute))
	}

	sizeInBAttribute, ok := attributes["size_in_b"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size_in_b is missing from object`)

		return nil, diags
	}

	sizeInBVal, ok := sizeInBAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size_in_b expected to be basetypes.Int64Value, was: %T`, sizeInBAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ScpUserIsosValue{
		Key:          keyVal,
		LastModified: lastModifiedVal,
		SizeInB:      sizeInBVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewScpUserIsosValueNull() ScpUserIsosValue {
	return ScpUserIsosValue{
		state: attr.ValueStateNull,
	}
}

func NewScpUserIsosValueUnknown() ScpUserIsosValue {
	return ScpUserIsosValue{
		state: attr.ValueStateUnknown,
	}
}

func NewScpUserIsosValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ScpUserIsosValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ScpUserIsosValue Attribute Value",
				"While creating a ScpUserIsosValue value, a missing attribute value was detected. "+
					"A ScpUserIsosValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScpUserIsosValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ScpUserIsosValue Attribute Type",
				"While creating a ScpUserIsosValue value, an invalid attribute value was detected. "+
					"A ScpUserIsosValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScpUserIsosValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ScpUserIsosValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ScpUserIsosValue Attribute Value",
				"While creating a ScpUserIsosValue value, an extra attribute value was detected. "+
					"A ScpUserIsosValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ScpUserIsosValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewScpUserIsosValueUnknown(), diags
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return NewScpUserIsosValueUnknown(), diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	lastModifiedAttribute, ok := attributes["last_modified"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_modified is missing from object`)

		return NewScpUserIsosValueUnknown(), diags
	}

	lastModifiedVal, ok := lastModifiedAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_modified expected to be basetypes.StringValue, was: %T`, lastModifiedAttribute))
	}

	sizeInBAttribute, ok := attributes["size_in_b"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size_in_b is missing from object`)

		return NewScpUserIsosValueUnknown(), diags
	}

	sizeInBVal, ok := sizeInBAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size_in_b expected to be basetypes.Int64Value, was: %T`, sizeInBAttribute))
	}

	if diags.HasError() {
		return NewScpUserIsosValueUnknown(), diags
	}

	return ScpUserIsosValue{
		Key:          keyVal,
		LastModified: lastModifiedVal,
		SizeInB:      sizeInBVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewScpUserIsosValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ScpUserIsosValue {
	object, diags := NewScpUserIsosValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewScpUserIsosValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ScpUserIsosType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewScpUserIsosValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewScpUserIsosValueUnknown(), nil
	}

	if in.IsNull() {
		return NewScpUserIsosValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewScpUserIsosValueMust(ScpUserIsosValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ScpUserIsosType) ValueType(ctx context.Context) attr.Value {
	return ScpUserIsosValue{}
}

var _ basetypes.ObjectValuable = ScpUserIsosValue{}

type ScpUserIsosValue struct {
	Key          basetypes.StringValue `tfsdk:"key"`
	LastModified basetypes.StringValue `tfsdk:"last_modified"`
	SizeInB      basetypes.Int64Value  `tfsdk:"size_in_b"`
	state        attr.ValueState
}

func (v ScpUserIsosValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["key"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["last_modified"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["size_in_b"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Key.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key"] = val

		val, err = v.LastModified.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["last_modified"] = val

		val, err = v.SizeInB.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["size_in_b"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ScpUserIsosValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ScpUserIsosValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ScpUserIsosValue) String() string {
	return "ScpUserIsosValue"
}

func (v ScpUserIsosValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"key":           basetypes.StringType{},
		"last_modified": basetypes.StringType{},
		"size_in_b":     basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"key":           v.Key,
			"last_modified": v.LastModified,
			"size_in_b":     v.SizeInB,
		})

	return objVal, diags
}

func (v ScpUserIsosValue) Equal(o attr.Value) bool {
	other, ok := o.(ScpUserIsosValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Key.Equal(other.Key) {
		return false
	}

	if !v.LastModified.Equal(other.LastModified) {
		return false
	}

	if !v.SizeInB.Equal(other.SizeInB) {
		return false
	}

	return true
}

func (v ScpUserIsosValue) Type(ctx context.Context) attr.Type {
	return ScpUserIsosType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ScpUserIsosValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"key":           basetypes.StringType{},
		"last_modified": basetypes.StringType{},
		"size_in_b":     basetypes.Int64Type{},
	}
}
