name: Tests

on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      - run: go mod download
      - uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          only-new-issues: true

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      - run: go mod download
      - run: go test -v -race ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      - run: go mod download
      - name: GoReleaser build
        uses: goreleaser/goreleaser-action@v6
        with:
          args: build --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
